/// 사용자에게 표시할 문구의 언어를 나타냅니다.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Language {
    /// 한국어 문구를 사용합니다.
    Korean,
    /// 영어 문구를 사용합니다.
    English,
    /// 스페인어 문구를 사용합니다.
    Spanish,
    /// 브라질 포르투갈어 문구를 사용합니다.
    PortugueseBrazil,
    /// 인도네시아어 문구를 사용합니다.
    Indonesian,
    /// 일본어 문구를 사용합니다.
    Japanese,
    /// 힌디어 문구를 사용합니다.
    Hindi,
    /// 독일어 문구를 사용합니다.
    German,
    /// 프랑스어 문구를 사용합니다.
    French,
    /// 베트남어 문구를 사용합니다.
    Vietnamese,
    /// 터키어 문구를 사용합니다.
    Turkish,
    /// 아랍어 문구를 사용합니다.
    Arabic,
}

impl Language {
    /// UI에서 지원하는 모든 언어를 표시 순서대로 반환합니다.
    pub const ALL: &'static [Self] = &[
        Self::Korean,
        Self::English,
        Self::Spanish,
        Self::PortugueseBrazil,
        Self::Indonesian,
        Self::Japanese,
        Self::Hindi,
        Self::German,
        Self::French,
        Self::Vietnamese,
        Self::Turkish,
        Self::Arabic,
    ];
}

/// 지원하는 모든 정적 지역화 문구의 식별자입니다.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LocalizationKey {
    /// 자동 갱신 상태입니다.
    Polling,
    /// 수동 갱신 상태입니다.
    Refreshing,
    /// 오래된 사용량 상태입니다.
    Stale,
    /// 사용량을 불러오지 못한 상태입니다.
    Unavailable,
    /// 새로 고침 메뉴입니다.
    MenuRefresh,
    /// 즉시 새로 고침 메뉴입니다.
    MenuRefreshNow,
    /// 갱신 간격 메뉴입니다.
    MenuRefreshInterval,
    /// 자동 시작 메뉴입니다.
    MenuAutostart,
    /// 시작 화면 메뉴입니다.
    MenuStartupView,
    /// 시작 시 위젯 표시 옵션입니다.
    MenuStartupWidget,
    /// 시작 시 트레이 전용 옵션입니다.
    MenuStartupTrayOnly,
    /// 자동 인증 갱신 메뉴입니다.
    MenuAuthRefresh,
    /// Codex 로그인 메뉴입니다.
    MenuLogin,
    /// 인증을 즉시 갱신하는 메뉴입니다.
    MenuAuthRefreshNow,
    /// 언어 메뉴입니다.
    MenuLanguage,
    /// 진단 메뉴입니다.
    MenuDiagnostics,
    /// 업데이트 확인 메뉴입니다.
    MenuUpdateCheck,
    /// 설정 메뉴입니다.
    MenuSettings,
    /// 종료 메뉴입니다.
    MenuExit,
    /// 위젯 표시 메뉴입니다.
    MenuShowWidget,
    /// 위젯 숨김 메뉴입니다.
    MenuHideWidget,
    /// 시작 시 위젯 표시 선택 메뉴입니다.
    MenuStartupWidgetChoice,
    /// 시작 시 트레이 전용 선택 메뉴입니다.
    MenuStartupTrayOnlyChoice,
    /// 모든 모니터 작업표시줄 표시 메뉴입니다.
    MenuTaskbarAll,
    /// 주 모니터 작업표시줄 표시 메뉴입니다.
    MenuTaskbarPrimary,
    /// 업데이트 가능 알림입니다.
    UpdateAvailable,
    /// 최신 상태 알림입니다.
    UpdateCurrent,
    /// 업데이트 확인 진행 상태 알림입니다.
    UpdateChecking,
    /// 업데이트 확인 실패 상태 알림입니다.
    UpdateFailed,
    /// 기본 창 제목입니다.
    WindowTitle,
    /// 설정 창 제목입니다.
    SettingsTitle,
    /// 진단 창 제목입니다.
    DiagnosticsTitle,
    /// 주 사용량 창 레이블입니다.
    PrimaryWindowLabel,
    /// 보조 사용량 창 레이블입니다.
    SecondaryWindowLabel,
    /// CLI 진단 문구입니다.
    DiagnosticCli,
    /// RPC 진단 문구입니다.
    DiagnosticRpc,
    /// 로그인 진단 문구입니다.
    DiagnosticLogin,
    /// 설정 진단 문구입니다.
    DiagnosticSettings,
    /// 프록시 진단 문구입니다.
    DiagnosticProxy,
    /// 작업 표시줄 진단 문구입니다.
    DiagnosticTaskbar,
    /// 남은 사용량 표시 전환 메뉴입니다.
    MenuShowRemaining,
    /// 주간 사용량 표시 전환 메뉴입니다.
    MenuShowWeekly,
}

impl LocalizationKey {
    /// 모든 문구 키를 빠짐없이 반환합니다.
    pub const ALL: &'static [Self] = &[
        Self::Polling,
        Self::Refreshing,
        Self::Stale,
        Self::Unavailable,
        Self::MenuRefresh,
        Self::MenuRefreshNow,
        Self::MenuRefreshInterval,
        Self::MenuAutostart,
        Self::MenuStartupView,
        Self::MenuStartupWidget,
        Self::MenuStartupTrayOnly,
        Self::MenuAuthRefresh,
        Self::MenuLogin,
        Self::MenuAuthRefreshNow,
        Self::MenuLanguage,
        Self::MenuDiagnostics,
        Self::MenuUpdateCheck,
        Self::MenuSettings,
        Self::MenuExit,
        Self::MenuShowWidget,
        Self::MenuHideWidget,
        Self::MenuStartupWidgetChoice,
        Self::MenuStartupTrayOnlyChoice,
        Self::MenuTaskbarAll,
        Self::MenuTaskbarPrimary,
        Self::UpdateAvailable,
        Self::UpdateCurrent,
        Self::UpdateChecking,
        Self::UpdateFailed,
        Self::WindowTitle,
        Self::SettingsTitle,
        Self::DiagnosticsTitle,
        Self::PrimaryWindowLabel,
        Self::SecondaryWindowLabel,
        Self::DiagnosticCli,
        Self::DiagnosticRpc,
        Self::DiagnosticLogin,
        Self::DiagnosticSettings,
        Self::DiagnosticProxy,
        Self::DiagnosticTaskbar,
        Self::MenuShowRemaining,
        Self::MenuShowWeekly,
    ];

    const fn index(self) -> usize {
        match self {
            Self::Polling => 0,
            Self::Refreshing => 1,
            Self::Stale => 2,
            Self::Unavailable => 3,
            Self::MenuRefresh => 4,
            Self::MenuRefreshNow => 5,
            Self::MenuRefreshInterval => 6,
            Self::MenuAutostart => 7,
            Self::MenuStartupView => 8,
            Self::MenuStartupWidget => 9,
            Self::MenuStartupTrayOnly => 10,
            Self::MenuAuthRefresh => 11,
            Self::MenuLogin => 12,
            Self::MenuAuthRefreshNow => 13,
            Self::MenuLanguage => 14,
            Self::MenuDiagnostics => 15,
            Self::MenuUpdateCheck => 16,
            Self::MenuSettings => 17,
            Self::MenuExit => 18,
            Self::MenuShowWidget => 19,
            Self::MenuHideWidget => 20,
            Self::MenuStartupWidgetChoice => 21,
            Self::MenuStartupTrayOnlyChoice => 22,
            Self::MenuTaskbarAll => 23,
            Self::MenuTaskbarPrimary => 24,
            Self::UpdateAvailable => 25,
            Self::UpdateCurrent => 26,
            Self::UpdateChecking => 27,
            Self::UpdateFailed => 28,
            Self::WindowTitle => 29,
            Self::SettingsTitle => 30,
            Self::DiagnosticsTitle => 31,
            Self::PrimaryWindowLabel => 32,
            Self::SecondaryWindowLabel => 33,
            Self::DiagnosticCli => 34,
            Self::DiagnosticRpc => 35,
            Self::DiagnosticLogin => 36,
            Self::DiagnosticSettings => 37,
            Self::DiagnosticProxy => 38,
            Self::DiagnosticTaskbar => 39,
            Self::MenuShowRemaining => 40,
            Self::MenuShowWeekly => 41,
        }
    }
}

const LOCALIZATION_KEY_COUNT: usize = 42;

const KOREAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "자동 갱신 중",
    "새로 고치는 중",
    "정보가 오래되었습니다",
    "사용량 정보를 사용할 수 없습니다",
    "새로 고침",
    "지금 갱신",
    "갱신 간격",
    "Windows 시작 시 실행",
    "시작 화면",
    "위젯 표시",
    "트레이에만 표시",
    "자동 인증 갱신",
    "Codex 로그인",
    "인증 갱신",
    "언어",
    "진단",
    "업데이트 확인",
    "설정",
    "종료",
    "위젯 표시",
    "위젯 숨기기",
    "시작: 위젯 표시",
    "시작: 트레이만",
    "위젯: 모든 모니터",
    "위젯: 주 모니터만",
    "새 업데이트를 사용할 수 있습니다",
    "최신 버전입니다",
    "업데이트를 확인하는 중입니다",
    "업데이트 확인에 실패했습니다",
    "Codex 사용량 모니터",
    "Codex 사용량 모니터 설정",
    "Codex 사용량 모니터 진단",
    "주 사용량 창",
    "보조 사용량 창",
    "Codex CLI를 확인할 수 없습니다",
    "Codex 서비스 요청에 실패했습니다",
    "로그인 상태를 확인할 수 없습니다",
    "설정을 읽거나 검증할 수 없습니다",
    "프록시 사용 여부를 확인했습니다",
    "작업 표시줄 상태를 확인할 수 없습니다",
    "남은 사용량 표시",
    "주간 사용량 표시",
];

const ENGLISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Polling",
    "Refreshing",
    "Usage data is stale",
    "Usage unavailable",
    "Refresh",
    "Refresh now",
    "Refresh interval",
    "Start with Windows",
    "Startup view",
    "Show widget",
    "Tray only",
    "Automatic authentication refresh",
    "Sign in to Codex",
    "Refresh authentication",
    "Language",
    "Diagnostics",
    "Check for updates",
    "Settings",
    "Exit",
    "Show widget",
    "Hide widget",
    "Startup: show widget",
    "Startup: tray only",
    "Widget: all monitors",
    "Widget: primary monitor only",
    "An update is available",
    "You are up to date",
    "Checking for updates",
    "Update check failed",
    "Codex Usage Monitor",
    "Codex Usage Monitor Settings",
    "Codex Usage Monitor Diagnostics",
    "Primary window",
    "Secondary window",
    "Codex CLI could not be verified",
    "Codex service request failed",
    "Login status could not be verified",
    "Settings could not be read or validated",
    "Proxy presence was checked",
    "Taskbar status could not be verified",
    "Show remaining usage",
    "Show weekly usage",
];

const SPANISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Consultando",
    "Actualizando",
    "Los datos de uso no están actualizados",
    "Uso no disponible",
    "Actualizar",
    "Actualizar ahora",
    "Intervalo de actualización",
    "Iniciar con Windows",
    "Vista inicial",
    "Mostrar widget",
    "Solo bandeja",
    "Actualización automática de autenticación",
    "Iniciar sesión en Codex",
    "Actualizar autenticación",
    "Idioma",
    "Diagnóstico",
    "Buscar actualizaciones",
    "Configuración",
    "Salir",
    "Mostrar widget",
    "Ocultar widget",
    "Inicio: mostrar widget",
    "Inicio: solo bandeja",
    "Widget: todos los monitores",
    "Widget: solo monitor principal",
    "Hay una actualización disponible",
    "Tienes la versión más reciente",
    "Buscando actualizaciones",
    "Error al buscar actualizaciones",
    "Monitor de uso de Codex",
    "Configuración del monitor de uso de Codex",
    "Diagnóstico del monitor de uso de Codex",
    "Ventana principal",
    "Ventana secundaria",
    "No se pudo verificar Codex CLI",
    "Falló la solicitud del servicio Codex",
    "No se pudo verificar el inicio de sesión",
    "No se pudo leer o validar la configuración",
    "Se comprobó la presencia de proxy",
    "No se pudo verificar el estado de la barra de tareas",
    "Mostrar uso restante",
    "Mostrar uso semanal",
];

const PORTUGUESE_BRAZIL_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Consultando",
    "Atualizando",
    "Os dados de uso estão desatualizados",
    "Uso indisponível",
    "Atualizar",
    "Atualizar agora",
    "Intervalo de atualização",
    "Iniciar com Windows",
    "Tela inicial",
    "Mostrar widget",
    "Somente bandeja",
    "Atualização automática da autenticação",
    "Entrar no Codex",
    "Atualizar autenticação",
    "Idioma",
    "Diagnóstico",
    "Verificar atualizações",
    "Configurações",
    "Sair",
    "Mostrar widget",
    "Ocultar widget",
    "Inicialização: mostrar widget",
    "Inicialização: somente bandeja",
    "Widget: todos os monitores",
    "Widget: somente monitor principal",
    "Há uma atualização disponível",
    "Você está na versão mais recente",
    "Verificando atualizações",
    "Falha ao verificar atualizações",
    "Monitor de uso do Codex",
    "Configurações do monitor de uso do Codex",
    "Diagnóstico do monitor de uso do Codex",
    "Janela principal",
    "Janela secundária",
    "Não foi possível verificar o Codex CLI",
    "Falha na solicitação do serviço Codex",
    "Não foi possível verificar o login",
    "Não foi possível ler ou validar as configurações",
    "A presença de proxy foi verificada",
    "Não foi possível verificar o status da barra de tarefas",
    "Mostrar uso restante",
    "Mostrar uso semanal",
];

const INDONESIAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Memeriksa",
    "Menyegarkan",
    "Data penggunaan sudah lama",
    "Penggunaan tidak tersedia",
    "Segarkan",
    "Segarkan sekarang",
    "Interval penyegaran",
    "Mulai bersama Windows",
    "Tampilan awal",
    "Tampilkan widget",
    "Hanya baki sistem",
    "Penyegaran autentikasi otomatis",
    "Masuk ke Codex",
    "Segarkan autentikasi",
    "Bahasa",
    "Diagnostik",
    "Periksa pembaruan",
    "Pengaturan",
    "Keluar",
    "Tampilkan widget",
    "Sembunyikan widget",
    "Awal: tampilkan widget",
    "Awal: hanya baki sistem",
    "Widget: semua monitor",
    "Widget: hanya monitor utama",
    "Pembaruan tersedia",
    "Anda sudah menggunakan versi terbaru",
    "Memeriksa pembaruan",
    "Pemeriksaan pembaruan gagal",
    "Monitor Penggunaan Codex",
    "Pengaturan Monitor Penggunaan Codex",
    "Diagnostik Monitor Penggunaan Codex",
    "Jendela utama",
    "Jendela sekunder",
    "Codex CLI tidak dapat diverifikasi",
    "Permintaan layanan Codex gagal",
    "Status login tidak dapat diverifikasi",
    "Pengaturan tidak dapat dibaca atau divalidasi",
    "Keberadaan proxy telah diperiksa",
    "Status taskbar tidak dapat diverifikasi",
    "Tampilkan sisa penggunaan",
    "Tampilkan penggunaan mingguan",
];

const JAPANESE_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "自動更新中",
    "更新中",
    "使用量データが古くなっています",
    "使用量を利用できません",
    "更新",
    "今すぐ更新",
    "更新間隔",
    "Windows 起動時に実行",
    "起動時の表示",
    "ウィジェットを表示",
    "トレイのみ",
    "認証の自動更新",
    "Codex にログイン",
    "認証を更新",
    "言語",
    "診断",
    "更新を確認",
    "設定",
    "終了",
    "ウィジェットを表示",
    "ウィジェットを隠す",
    "起動: ウィジェットを表示",
    "起動: トレイのみ",
    "ウィジェット: すべてのモニター",
    "ウィジェット: メインモニターのみ",
    "新しい更新があります",
    "最新バージョンです",
    "更新を確認中",
    "更新の確認に失敗しました",
    "Codex 使用量モニター",
    "Codex 使用量モニター設定",
    "Codex 使用量モニター診断",
    "メインウィンドウ",
    "サブウィンドウ",
    "Codex CLI を確認できませんでした",
    "Codex サービス要求に失敗しました",
    "ログイン状態を確認できませんでした",
    "設定を読み取りまたは検証できませんでした",
    "プロキシの有無を確認しました",
    "タスクバーの状態を確認できませんでした",
    "残り使用量を表示",
    "週間使用量を表示",
];

const HINDI_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "पोलिंग",
    "रीफ़्रेश हो रहा है",
    "उपयोग डेटा पुराना है",
    "उपयोग उपलब्ध नहीं",
    "रीफ़्रेश",
    "अभी रीफ़्रेश करें",
    "रीफ़्रेश अंतराल",
    "Windows के साथ शुरू करें",
    "स्टार्टअप दृश्य",
    "विजेट दिखाएँ",
    "केवल ट्रे",
    "स्वचालित प्रमाणीकरण रीफ़्रेश",
    "Codex में साइन इन करें",
    "प्रमाणीकरण रीफ़्रेश करें",
    "भाषा",
    "निदान",
    "अपडेट जाँचें",
    "सेटिंग्स",
    "बाहर निकलें",
    "विजेट दिखाएँ",
    "विजेट छिपाएँ",
    "स्टार्टअप: विजेट दिखाएँ",
    "स्टार्टअप: केवल ट्रे",
    "विजेट: सभी मॉनिटर",
    "विजेट: केवल मुख्य मॉनिटर",
    "अपडेट उपलब्ध है",
    "आप नवीनतम संस्करण पर हैं",
    "अपडेट जाँचे जा रहे हैं",
    "अपडेट जाँच विफल रही",
    "Codex उपयोग मॉनिटर",
    "Codex उपयोग मॉनिटर सेटिंग्स",
    "Codex उपयोग मॉनिटर निदान",
    "मुख्य विंडो",
    "द्वितीयक विंडो",
    "Codex CLI सत्यापित नहीं हो सका",
    "Codex सेवा अनुरोध विफल रहा",
    "लॉगिन स्थिति सत्यापित नहीं हो सकी",
    "सेटिंग्स पढ़ी या सत्यापित नहीं की जा सकीं",
    "प्रॉक्सी की उपस्थिति जाँची गई",
    "टास्कबार स्थिति सत्यापित नहीं हो सकी",
    "शेष उपयोग दिखाएँ",
    "साप्ताहिक उपयोग दिखाएँ",
];

const GERMAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Abfrage läuft",
    "Aktualisieren",
    "Nutzungsdaten sind veraltet",
    "Nutzung nicht verfügbar",
    "Aktualisieren",
    "Jetzt aktualisieren",
    "Aktualisierungsintervall",
    "Mit Windows starten",
    "Startansicht",
    "Widget anzeigen",
    "Nur Infobereich",
    "Automatische Authentifizierung aktualisieren",
    "Bei Codex anmelden",
    "Authentifizierung aktualisieren",
    "Sprache",
    "Diagnose",
    "Nach Updates suchen",
    "Einstellungen",
    "Beenden",
    "Widget anzeigen",
    "Widget ausblenden",
    "Start: Widget anzeigen",
    "Start: nur Infobereich",
    "Widget: alle Monitore",
    "Widget: nur Hauptmonitor",
    "Ein Update ist verfügbar",
    "Sie sind auf dem neuesten Stand",
    "Updates werden gesucht",
    "Updateprüfung fehlgeschlagen",
    "Codex-Nutzungsmonitor",
    "Einstellungen für Codex-Nutzungsmonitor",
    "Diagnose des Codex-Nutzungsmonitors",
    "Hauptfenster",
    "Nebenfenster",
    "Codex CLI konnte nicht verifiziert werden",
    "Codex-Dienstanforderung fehlgeschlagen",
    "Anmeldestatus konnte nicht verifiziert werden",
    "Einstellungen konnten nicht gelesen oder validiert werden",
    "Proxy-Präsenz wurde geprüft",
    "Taskleistenstatus konnte nicht verifiziert werden",
    "Verbleibende Nutzung anzeigen",
    "Wöchentliche Nutzung anzeigen",
];

const FRENCH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Interrogation",
    "Actualisation",
    "Les données d'utilisation sont obsolètes",
    "Utilisation indisponible",
    "Actualiser",
    "Actualiser maintenant",
    "Intervalle d'actualisation",
    "Démarrer avec Windows",
    "Vue au démarrage",
    "Afficher le widget",
    "Zone de notification seule",
    "Actualisation automatique de l'authentification",
    "Se connecter à Codex",
    "Actualiser l'authentification",
    "Langue",
    "Diagnostics",
    "Rechercher des mises à jour",
    "Paramètres",
    "Quitter",
    "Afficher le widget",
    "Masquer le widget",
    "Démarrage: afficher le widget",
    "Démarrage: zone de notification seule",
    "Widget: tous les moniteurs",
    "Widget: moniteur principal seul",
    "Une mise à jour est disponible",
    "Vous êtes à jour",
    "Recherche de mises à jour",
    "Échec de la recherche de mises à jour",
    "Moniteur d'utilisation Codex",
    "Paramètres du moniteur d'utilisation Codex",
    "Diagnostics du moniteur d'utilisation Codex",
    "Fenêtre principale",
    "Fenêtre secondaire",
    "Codex CLI n'a pas pu être vérifié",
    "La requête du service Codex a échoué",
    "L'état de connexion n'a pas pu être vérifié",
    "Les paramètres n'ont pas pu être lus ou validés",
    "La présence d'un proxy a été vérifiée",
    "L'état de la barre des tâches n'a pas pu être vérifié",
    "Afficher l'utilisation restante",
    "Afficher l'utilisation hebdomadaire",
];

const VIETNAMESE_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Đang thăm dò",
    "Đang làm mới",
    "Dữ liệu sử dụng đã cũ",
    "Không có thông tin sử dụng",
    "Làm mới",
    "Làm mới ngay",
    "Khoảng thời gian làm mới",
    "Khởi động cùng Windows",
    "Màn hình khởi động",
    "Hiển thị widget",
    "Chỉ khay hệ thống",
    "Tự động làm mới xác thực",
    "Đăng nhập vào Codex",
    "Làm mới xác thực",
    "Ngôn ngữ",
    "Chẩn đoán",
    "Kiểm tra cập nhật",
    "Cài đặt",
    "Thoát",
    "Hiển thị widget",
    "Ẩn widget",
    "Khởi động: hiển thị widget",
    "Khởi động: chỉ khay hệ thống",
    "Widget: tất cả màn hình",
    "Widget: chỉ màn hình chính",
    "Có bản cập nhật mới",
    "Bạn đang dùng phiên bản mới nhất",
    "Đang kiểm tra cập nhật",
    "Kiểm tra cập nhật thất bại",
    "Bộ theo dõi sử dụng Codex",
    "Cài đặt bộ theo dõi sử dụng Codex",
    "Chẩn đoán bộ theo dõi sử dụng Codex",
    "Cửa sổ chính",
    "Cửa sổ phụ",
    "Không thể xác minh Codex CLI",
    "Yêu cầu dịch vụ Codex thất bại",
    "Không thể xác minh trạng thái đăng nhập",
    "Không thể đọc hoặc xác thực cài đặt",
    "Đã kiểm tra sự hiện diện của proxy",
    "Không thể xác minh trạng thái thanh tác vụ",
    "Hiển thị mức sử dụng còn lại",
    "Hiển thị mức sử dụng hằng tuần",
];

const TURKISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Sorgulanıyor",
    "Yenileniyor",
    "Kullanım verileri eski",
    "Kullanım kullanılamıyor",
    "Yenile",
    "Şimdi yenile",
    "Yenileme aralığı",
    "Windows ile başlat",
    "Başlangıç görünümü",
    "Widget'ı göster",
    "Yalnızca tepsi",
    "Otomatik kimlik doğrulama yenileme",
    "Codex'te oturum aç",
    "Kimlik doğrulamayı yenile",
    "Dil",
    "Tanılama",
    "Güncellemeleri denetle",
    "Ayarlar",
    "Çıkış",
    "Widget'ı göster",
    "Widget'ı gizle",
    "Başlangıç: widget'ı göster",
    "Başlangıç: yalnızca tepsi",
    "Widget: tüm monitörler",
    "Widget: yalnızca ana monitör",
    "Bir güncelleme mevcut",
    "Güncelsiniz",
    "Güncellemeler denetleniyor",
    "Güncelleme denetimi başarısız",
    "Codex Kullanım Monitörü",
    "Codex Kullanım Monitörü Ayarları",
    "Codex Kullanım Monitörü Tanılaması",
    "Birincil pencere",
    "İkincil pencere",
    "Codex CLI doğrulanamadı",
    "Codex hizmet isteği başarısız",
    "Oturum açma durumu doğrulanamadı",
    "Ayarlar okunamadı veya doğrulanamadı",
    "Proxy varlığı denetlendi",
    "Görev çubuğu durumu doğrulanamadı",
    "Kalan kullanımı göster",
    "Haftalık kullanımı göster",
];

const ARABIC_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "جارٍ الاستعلام",
    "جارٍ التحديث",
    "بيانات الاستخدام قديمة",
    "الاستخدام غير متاح",
    "تحديث",
    "تحديث الآن",
    "فاصل التحديث",
    "البدء مع Windows",
    "عرض بدء التشغيل",
    "إظهار الويدجت",
    "علبة النظام فقط",
    "تحديث المصادقة تلقائيًا",
    "تسجيل الدخول إلى Codex",
    "تحديث المصادقة",
    "اللغة",
    "التشخيصات",
    "التحقق من التحديثات",
    "الإعدادات",
    "خروج",
    "إظهار الويدجت",
    "إخفاء الويدجت",
    "بدء التشغيل: إظهار الويدجت",
    "بدء التشغيل: علبة النظام فقط",
    "الويدجت: كل الشاشات",
    "الويدجت: الشاشة الرئيسية فقط",
    "يتوفر تحديث جديد",
    "أنت تستخدم أحدث إصدار",
    "جارٍ التحقق من التحديثات",
    "فشل التحقق من التحديثات",
    "مراقب استخدام Codex",
    "إعدادات مراقب استخدام Codex",
    "تشخيصات مراقب استخدام Codex",
    "النافذة الرئيسية",
    "النافذة الثانوية",
    "تعذر التحقق من Codex CLI",
    "فشل طلب خدمة Codex",
    "تعذر التحقق من حالة تسجيل الدخول",
    "تعذرت قراءة الإعدادات أو التحقق منها",
    "تم التحقق من وجود الوكيل",
    "تعذر التحقق من حالة شريط المهام",
    "إظهار الاستخدام المتبقي",
    "إظهار الاستخدام الأسبوعي",
];

/// 지정한 언어와 키에 해당하는 정적 사용자 문구를 반환합니다.
///
/// 매개변수 `key`는 표시할 문구 식별자이고 `language`는 반환 언어입니다.
/// 반환값은 프로그램 전체에서 재사용 가능한 정적 문자열입니다.
pub fn localized_text(key: LocalizationKey, language: Language) -> &'static str {
    let index = key.index();
    match language {
        Language::Korean => KOREAN_TEXT[index],
        Language::English => ENGLISH_TEXT[index],
        Language::Spanish => SPANISH_TEXT[index],
        Language::PortugueseBrazil => PORTUGUESE_BRAZIL_TEXT[index],
        Language::Indonesian => INDONESIAN_TEXT[index],
        Language::Japanese => JAPANESE_TEXT[index],
        Language::Hindi => HINDI_TEXT[index],
        Language::German => GERMAN_TEXT[index],
        Language::French => FRENCH_TEXT[index],
        Language::Vietnamese => VIETNAMESE_TEXT[index],
        Language::Turkish => TURKISH_TEXT[index],
        Language::Arabic => ARABIC_TEXT[index],
    }
}

/// 갱신 간격 값을 트레이 메뉴에 표시할 지역화 문구로 만듭니다.
///
/// `minutes`는 지원되는 자동 갱신 간격이며, 호출자가 메뉴 동작 검증을 별도로 수행합니다.
pub(crate) fn localized_refresh_interval_menu_text(minutes: u32, language: Language) -> String {
    match language {
        Language::Korean => format!("갱신 간격: {minutes}분"),
        Language::English => format!("Refresh interval: {minutes} min"),
        Language::Spanish => format!("Intervalo de actualización: {minutes} min"),
        Language::PortugueseBrazil => format!("Intervalo de atualização: {minutes} min"),
        Language::Indonesian => format!("Interval penyegaran: {minutes} mnt"),
        Language::Japanese => format!("更新間隔: {minutes}分"),
        Language::Hindi => format!("रीफ़्रेश अंतराल: {minutes} मिनट"),
        Language::German => format!("Aktualisierungsintervall: {minutes} Min."),
        Language::French => format!("Intervalle d'actualisation: {minutes} min"),
        Language::Vietnamese => format!("Khoảng thời gian làm mới: {minutes} phút"),
        Language::Turkish => format!("Yenileme aralığı: {minutes} dk"),
        Language::Arabic => format!("فاصل التحديث: {minutes} دقيقة"),
    }
}

#[cfg(test)]
mod tests {
    use super::{localized_refresh_interval_menu_text, localized_text, Language, LocalizationKey};

    #[test]
    fn every_key_has_a_nonempty_translation() {
        for key in LocalizationKey::ALL {
            for language in Language::ALL {
                assert!(!localized_text(*key, *language).trim().is_empty());
            }
        }
    }

    #[test]
    fn refresh_interval_menu_text_includes_value_and_unit() {
        assert_eq!(
            localized_refresh_interval_menu_text(15, Language::Korean),
            "갱신 간격: 15분"
        );
        assert_eq!(
            localized_refresh_interval_menu_text(15, Language::English),
            "Refresh interval: 15 min"
        );
        for language in Language::ALL {
            let text = localized_refresh_interval_menu_text(15, *language);
            assert!(text.contains("15"), "{language:?}: {text}");
        }
    }
}
