/// 사용자에게 표시할 문구의 언어를 나타냅니다.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Language {
    /// 한국어 문구를 사용합니다.
    Korean,
    /// 영어 문구를 사용합니다.
    English,
    /// 스페인어 문구를 사용합니다.
    Spanish,
    /// 브라질 포르투갈어 문구를 사용합니다.
    PortugueseBrazil,
    /// 인도네시아어 문구를 사용합니다.
    Indonesian,
    /// 일본어 문구를 사용합니다.
    Japanese,
    /// 힌디어 문구를 사용합니다.
    Hindi,
    /// 독일어 문구를 사용합니다.
    German,
    /// 프랑스어 문구를 사용합니다.
    French,
    /// 베트남어 문구를 사용합니다.
    Vietnamese,
    /// 터키어 문구를 사용합니다.
    Turkish,
    /// 아랍어 문구를 사용합니다.
    Arabic,
}

impl Language {
    /// UI에서 지원하는 모든 언어를 표시 순서대로 반환합니다.
    pub const ALL: &'static [Self] = &[
        Self::Korean,
        Self::English,
        Self::Spanish,
        Self::PortugueseBrazil,
        Self::Indonesian,
        Self::Japanese,
        Self::Hindi,
        Self::German,
        Self::French,
        Self::Vietnamese,
        Self::Turkish,
        Self::Arabic,
    ];
}

/// 지원하는 모든 정적 지역화 문구의 식별자입니다.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LocalizationKey {
    /// 자동 갱신 상태입니다.
    Polling,
    /// 수동 갱신 상태입니다.
    Refreshing,
    /// 오래된 사용량 상태입니다.
    Stale,
    /// 사용량을 불러오지 못한 상태입니다.
    Unavailable,
    /// 갱신 관련 동작을 묶은 메뉴입니다.
    MenuRefresh,
    /// 즉시 새로 고침 메뉴입니다.
    MenuRefreshNow,
    /// 갱신 간격 메뉴입니다.
    MenuRefreshInterval,
    /// 자동 시작 메뉴입니다.
    MenuAutostart,
    /// 시작 화면 메뉴입니다.
    MenuStartupView,
    /// 시작 시 위젯 표시 옵션입니다.
    MenuStartupWidget,
    /// 시작 시 트레이 전용 옵션입니다.
    MenuStartupTrayOnly,
    /// 자동 인증 갱신 메뉴입니다.
    MenuAuthRefresh,
    /// Codex 로그인 메뉴입니다.
    MenuLogin,
    /// 인증을 즉시 갱신하는 메뉴입니다.
    MenuAuthRefreshNow,
    /// 언어 메뉴입니다.
    MenuLanguage,
    /// 언어 자동 선택 항목입니다.
    MenuLanguageAutomaticChoice,
    /// 진단 메뉴입니다.
    MenuDiagnostics,
    /// 업데이트 확인 메뉴입니다.
    MenuUpdateCheck,
    /// 설정 메뉴입니다.
    MenuSettings,
    /// 종료 메뉴입니다.
    MenuExit,
    /// 위젯 표시 메뉴입니다.
    MenuShowWidget,
    /// 위젯 숨김 메뉴입니다.
    MenuHideWidget,
    /// 시작 시 위젯 표시 선택 메뉴입니다.
    MenuStartupWidgetChoice,
    /// 시작 시 트레이 전용 선택 메뉴입니다.
    MenuStartupTrayOnlyChoice,
    /// 모든 모니터 작업표시줄 표시 메뉴입니다.
    MenuTaskbarAll,
    /// 주 모니터 작업표시줄 표시 메뉴입니다.
    MenuTaskbarPrimary,
    /// 위젯 표시 위치 메뉴입니다.
    MenuWidgetPlacement,
    /// 모든 모니터 선택 항목입니다.
    MenuTaskbarAllChoice,
    /// 주 모니터 선택 항목입니다.
    MenuTaskbarPrimaryChoice,
    /// 업데이트 가능 알림입니다.
    UpdateAvailable,
    /// 최신 상태 알림입니다.
    UpdateCurrent,
    /// 업데이트 확인 진행 상태 알림입니다.
    UpdateChecking,
    /// 업데이트 확인 실패 상태 알림입니다.
    UpdateFailed,
    /// 기본 창 제목입니다.
    WindowTitle,
    /// 설정 창 제목입니다.
    SettingsTitle,
    /// 진단 창 제목입니다.
    DiagnosticsTitle,
    /// 주 사용량 창 레이블입니다.
    PrimaryWindowLabel,
    /// 보조 사용량 창 레이블입니다.
    SecondaryWindowLabel,
    /// CLI 진단 문구입니다.
    DiagnosticCli,
    /// RPC 진단 문구입니다.
    DiagnosticRpc,
    /// 로그인 진단 문구입니다.
    DiagnosticLogin,
    /// 설정 진단 문구입니다.
    DiagnosticSettings,
    /// 프록시 진단 문구입니다.
    DiagnosticProxy,
    /// 작업 표시줄 진단 문구입니다.
    DiagnosticTaskbar,
    /// 남은 사용량으로 표시하는 전환 메뉴입니다.
    MenuShowRemaining,
    /// 주간 사용량 표시 전환 메뉴입니다.
    MenuShowWeekly,
    /// 새 버전과 GitHub 릴리스 페이지 열기를 확인하는 문구입니다.
    UpdateAvailablePrompt,
    /// 업데이트 확인 실패 후 복구 방법을 안내하는 문구입니다.
    UpdateFailedHelp,
    /// GitHub 릴리스 페이지 열기 실패 안내입니다.
    UpdateOpenFailed,
    /// 사용량 프로필 선택 메뉴입니다.
    MenuUsageProfiles,
    /// 사용량 프로필 추가 메뉴입니다.
    MenuAddUsageProfile,
    /// 사용량 프로필 관리 메뉴입니다.
    MenuManageUsageProfiles,
    /// 시스템 Codex 프로필 이름입니다.
    UsageProfileSystem,
    /// 현재 표시 중인 프로필 상태입니다.
    UsageProfileDisplayed,
    /// Codex CLI 로그인이 바뀌지 않는다는 안내입니다.
    UsageProfileCliUnchanged,
    /// 프로필 로그인이 필요하다는 상태입니다.
    UsageProfileLoginRequired,
    /// 사용량 프로필 추가 창 제목입니다.
    UsageProfileAddTitle,
    /// 브라우저에서 계정을 확인하라는 안내입니다.
    UsageProfileConfirmBrowserAccount,
    /// 프로필 이름 변경 동작입니다.
    UsageProfileRename,
    /// 프로필 로그인 동작입니다.
    UsageProfileLogin,
    /// 프로필 로그아웃 동작입니다.
    UsageProfileLogout,
    /// 프로필 삭제 동작입니다.
    UsageProfileDelete,
    /// 프로필 삭제 확인 문구입니다.
    UsageProfileDeleteConfirm,
    /// 프로필 개수 제한 안내입니다.
    UsageProfileLimitReached,
    /// 프로필 관리 대화상자의 닫기 동작입니다.
    UsageProfileClose,
    /// 프로필 표시 이름 입력 레이블입니다.
    UsageProfileName,
    /// 프로필 표시 이름 검증 실패 안내입니다.
    UsageProfileInvalidLabel,
    /// 프로필 로그인과 기존 CLI·IDE 로그인의 격리 안내입니다.
    UsageProfileCliIdeUnchanged,
    /// 로컬 프로필 데이터 삭제의 복구 불가 안내입니다.
    UsageProfileDeleteIrrecoverable,
    /// 프로필 대화상자 작업 실패의 안전한 안내입니다.
    UsageProfileOperationFailed,
    /// 프로필 추가 입력창을 닫는 동작입니다.
    UsageProfileCancel,
    /// 프로필별 사용 가능한 리셋권 수를 나타내는 레이블입니다.
    UsageProfileResetCredits,
    /// 프로필별 한도 소모율을 나타내는 레이블입니다.
    UsageProfileUsed,
    /// 프로필별 리셋권 또는 한도의 종료 시각을 나타내는 레이블입니다.
    UsageProfileEnds,
    /// 사용량 소진 예측 하위 메뉴입니다.
    MenuUsageForecast,
    /// 사용량 소진 예측 기록과 표시를 전환하는 메뉴입니다.
    MenuUsageForecastToggle,
    /// 사용량 소진 예측 기록을 삭제하는 메뉴입니다.
    MenuUsageForecastClearHistory,
    /// 사용량 소진 예측 기록 삭제 확인 문구입니다.
    UsageForecastClearConfirm,
    /// 예측 표본을 수집 중인 상태입니다.
    UsageForecastCollecting,
    /// 사용량 변화가 작아 예측하지 못하는 상태입니다.
    UsageForecastInsufficientActivity,
    /// 현재 속도로 소진까지 걸리는 시간을 나타내는 문구입니다.
    UsageForecastEstimate,
    /// 초기화 전에 소진할 가능성을 나타내는 문구입니다.
    UsageForecastBeforeReset,
    /// 초기화 시 예상 잔여 사용량을 나타내는 문구입니다.
    UsageForecastAtReset,
    /// 소진 시점이 먼 경우의 문구입니다.
    UsageForecastLongTerm,
    /// 현재 한도가 이미 소진된 상태입니다.
    UsageForecastExhausted,
    /// 예측 표본이 오래된 상태입니다.
    UsageForecastStale,
    /// 예측 입력이 유효하지 않은 상태입니다.
    UsageForecastInvalid,
    /// 1분을 나타내는 단수 단위입니다.
    UsageForecastMinuteOne,
    /// 2분 이상을 나타내는 복수 단위입니다.
    UsageForecastMinuteOther,
    /// 1시간을 나타내는 단수 단위입니다.
    UsageForecastHourOne,
    /// 2시간 이상을 나타내는 복수 단위입니다.
    UsageForecastHourOther,
    /// 1일을 나타내는 단수 단위입니다.
    UsageForecastDayOne,
    /// 2일 이상을 나타내는 복수 단위입니다.
    UsageForecastDayOther,
    /// 여유로운 소비 속도를 나타내는 문구입니다.
    UsagePaceComfortable,
    /// 보통 소비 속도를 나타내는 문구입니다.
    UsagePaceNormal,
    /// 빠른 소비 속도를 나타내는 문구입니다.
    UsagePaceFast,
    /// 소비 속도 측정에 필요한 표본 진행 상태입니다.
    UsagePaceMeasuring,
    /// 소비 속도를 판단할 수 없는 상태입니다.
    UsagePaceUnavailable,
    /// 소비 속도 표시가 꺼진 상태입니다.
    UsagePaceDisabled,
    /// 최근 관측 기간의 사용량과 시간당 속도 설명입니다.
    UsagePaceRecentActivity,
    /// 현재 속도에서 초기화 시 예상 잔여 사용량입니다.
    UsagePaceExpectedRemaining,
    /// 현재 속도에서 초기화 전 소진 위험을 나타내는 문구입니다.
    UsagePaceBeforeReset,
    /// 새 버전을 설치할지 확인하는 문구입니다.
    UpdateInstallPrompt,
    /// 업데이트를 즉시 설치하는 동작입니다.
    UpdateActionInstall,
    /// 발견한 버전을 건너뛰는 동작입니다.
    UpdateActionSkipVersion,
    /// 업데이트 다운로드 진행 상태입니다.
    UpdateDownloading,
    /// 업데이트 설치 및 재시작 진행 상태입니다.
    UpdateInstalling,
    /// 업데이트 다운로드 실패 안내입니다.
    UpdateDownloadFailed,
    /// 다운로드한 업데이트 검증 실패 안내입니다.
    UpdateVerificationFailed,
    /// 업데이트 설치 실패 안내입니다.
    UpdateInstallFailed,
    /// 공식 릴리스가 아닌 빌드의 자동 업데이트 제한 안내입니다.
    UpdateUnofficialBuildWarning,
}

impl LocalizationKey {
    /// 모든 문구 키를 빠짐없이 반환합니다.
    pub const ALL: &'static [Self] = &[
        Self::Polling,
        Self::Refreshing,
        Self::Stale,
        Self::Unavailable,
        Self::MenuRefresh,
        Self::MenuRefreshNow,
        Self::MenuRefreshInterval,
        Self::MenuAutostart,
        Self::MenuStartupView,
        Self::MenuStartupWidget,
        Self::MenuStartupTrayOnly,
        Self::MenuAuthRefresh,
        Self::MenuLogin,
        Self::MenuAuthRefreshNow,
        Self::MenuLanguage,
        Self::MenuLanguageAutomaticChoice,
        Self::MenuDiagnostics,
        Self::MenuUpdateCheck,
        Self::MenuSettings,
        Self::MenuExit,
        Self::MenuShowWidget,
        Self::MenuHideWidget,
        Self::MenuStartupWidgetChoice,
        Self::MenuStartupTrayOnlyChoice,
        Self::MenuTaskbarAll,
        Self::MenuTaskbarPrimary,
        Self::MenuWidgetPlacement,
        Self::MenuTaskbarAllChoice,
        Self::MenuTaskbarPrimaryChoice,
        Self::UpdateAvailable,
        Self::UpdateCurrent,
        Self::UpdateChecking,
        Self::UpdateFailed,
        Self::WindowTitle,
        Self::SettingsTitle,
        Self::DiagnosticsTitle,
        Self::PrimaryWindowLabel,
        Self::SecondaryWindowLabel,
        Self::DiagnosticCli,
        Self::DiagnosticRpc,
        Self::DiagnosticLogin,
        Self::DiagnosticSettings,
        Self::DiagnosticProxy,
        Self::DiagnosticTaskbar,
        Self::MenuShowRemaining,
        Self::MenuShowWeekly,
        Self::UpdateAvailablePrompt,
        Self::UpdateFailedHelp,
        Self::UpdateOpenFailed,
        Self::MenuUsageProfiles,
        Self::MenuAddUsageProfile,
        Self::MenuManageUsageProfiles,
        Self::UsageProfileSystem,
        Self::UsageProfileDisplayed,
        Self::UsageProfileCliUnchanged,
        Self::UsageProfileLoginRequired,
        Self::UsageProfileAddTitle,
        Self::UsageProfileConfirmBrowserAccount,
        Self::UsageProfileRename,
        Self::UsageProfileLogin,
        Self::UsageProfileLogout,
        Self::UsageProfileDelete,
        Self::UsageProfileDeleteConfirm,
        Self::UsageProfileLimitReached,
        Self::UsageProfileClose,
        Self::UsageProfileName,
        Self::UsageProfileInvalidLabel,
        Self::UsageProfileCliIdeUnchanged,
        Self::UsageProfileDeleteIrrecoverable,
        Self::UsageProfileOperationFailed,
        Self::UsageProfileCancel,
        Self::UsageProfileResetCredits,
        Self::UsageProfileUsed,
        Self::UsageProfileEnds,
        Self::MenuUsageForecast,
        Self::MenuUsageForecastToggle,
        Self::MenuUsageForecastClearHistory,
        Self::UsageForecastClearConfirm,
        Self::UsageForecastCollecting,
        Self::UsageForecastInsufficientActivity,
        Self::UsageForecastEstimate,
        Self::UsageForecastBeforeReset,
        Self::UsageForecastAtReset,
        Self::UsageForecastLongTerm,
        Self::UsageForecastExhausted,
        Self::UsageForecastStale,
        Self::UsageForecastInvalid,
        Self::UsageForecastMinuteOne,
        Self::UsageForecastMinuteOther,
        Self::UsageForecastHourOne,
        Self::UsageForecastHourOther,
        Self::UsageForecastDayOne,
        Self::UsageForecastDayOther,
        Self::UsagePaceComfortable,
        Self::UsagePaceNormal,
        Self::UsagePaceFast,
        Self::UsagePaceMeasuring,
        Self::UsagePaceUnavailable,
        Self::UsagePaceDisabled,
        Self::UsagePaceRecentActivity,
        Self::UsagePaceExpectedRemaining,
        Self::UsagePaceBeforeReset,
        Self::UpdateInstallPrompt,
        Self::UpdateActionInstall,
        Self::UpdateActionSkipVersion,
        Self::UpdateDownloading,
        Self::UpdateInstalling,
        Self::UpdateDownloadFailed,
        Self::UpdateVerificationFailed,
        Self::UpdateInstallFailed,
        Self::UpdateUnofficialBuildWarning,
    ];

    const fn index(self) -> usize {
        match self {
            Self::Polling => 0,
            Self::Refreshing => 1,
            Self::Stale => 2,
            Self::Unavailable => 3,
            Self::MenuRefresh => 4,
            Self::MenuRefreshNow => 5,
            Self::MenuRefreshInterval => 6,
            Self::MenuAutostart => 7,
            Self::MenuStartupView => 8,
            Self::MenuStartupWidget => 9,
            Self::MenuStartupTrayOnly => 10,
            Self::MenuAuthRefresh => 11,
            Self::MenuLogin => 12,
            Self::MenuAuthRefreshNow => 13,
            Self::MenuLanguage => 14,
            Self::MenuLanguageAutomaticChoice => 15,
            Self::MenuDiagnostics => 16,
            Self::MenuUpdateCheck => 17,
            Self::MenuSettings => 18,
            Self::MenuExit => 19,
            Self::MenuShowWidget => 20,
            Self::MenuHideWidget => 21,
            Self::MenuStartupWidgetChoice => 22,
            Self::MenuStartupTrayOnlyChoice => 23,
            Self::MenuTaskbarAll => 24,
            Self::MenuTaskbarPrimary => 25,
            Self::MenuWidgetPlacement => 26,
            Self::MenuTaskbarAllChoice => 27,
            Self::MenuTaskbarPrimaryChoice => 28,
            Self::UpdateAvailable => 29,
            Self::UpdateCurrent => 30,
            Self::UpdateChecking => 31,
            Self::UpdateFailed => 32,
            Self::WindowTitle => 33,
            Self::SettingsTitle => 34,
            Self::DiagnosticsTitle => 35,
            Self::PrimaryWindowLabel => 36,
            Self::SecondaryWindowLabel => 37,
            Self::DiagnosticCli => 38,
            Self::DiagnosticRpc => 39,
            Self::DiagnosticLogin => 40,
            Self::DiagnosticSettings => 41,
            Self::DiagnosticProxy => 42,
            Self::DiagnosticTaskbar => 43,
            Self::MenuShowRemaining => 44,
            Self::MenuShowWeekly => 45,
            Self::UpdateAvailablePrompt => 46,
            Self::UpdateFailedHelp => 47,
            Self::UpdateOpenFailed => 48,
            Self::MenuUsageProfiles => 49,
            Self::MenuAddUsageProfile => 50,
            Self::MenuManageUsageProfiles => 51,
            Self::UsageProfileSystem => 52,
            Self::UsageProfileDisplayed => 53,
            Self::UsageProfileCliUnchanged => 54,
            Self::UsageProfileLoginRequired => 55,
            Self::UsageProfileAddTitle => 56,
            Self::UsageProfileConfirmBrowserAccount => 57,
            Self::UsageProfileRename => 58,
            Self::UsageProfileLogin => 59,
            Self::UsageProfileLogout => 60,
            Self::UsageProfileDelete => 61,
            Self::UsageProfileDeleteConfirm => 62,
            Self::UsageProfileLimitReached => 63,
            Self::UsageProfileClose => 64,
            Self::UsageProfileName => 65,
            Self::UsageProfileInvalidLabel => 66,
            Self::UsageProfileCliIdeUnchanged => 67,
            Self::UsageProfileDeleteIrrecoverable => 68,
            Self::UsageProfileOperationFailed => 69,
            Self::UsageProfileCancel => 70,
            Self::UsageProfileResetCredits => 71,
            Self::UsageProfileUsed => 72,
            Self::UsageProfileEnds => 73,
            Self::MenuUsageForecast => 74,
            Self::MenuUsageForecastToggle => 75,
            Self::MenuUsageForecastClearHistory => 76,
            Self::UsageForecastClearConfirm => 77,
            Self::UsageForecastCollecting => 78,
            Self::UsageForecastInsufficientActivity => 79,
            Self::UsageForecastEstimate => 80,
            Self::UsageForecastBeforeReset => 81,
            Self::UsageForecastAtReset => 82,
            Self::UsageForecastLongTerm => 83,
            Self::UsageForecastExhausted => 84,
            Self::UsageForecastStale => 85,
            Self::UsageForecastInvalid => 86,
            Self::UsageForecastMinuteOne => 87,
            Self::UsageForecastMinuteOther => 88,
            Self::UsageForecastHourOne => 89,
            Self::UsageForecastHourOther => 90,
            Self::UsageForecastDayOne => 91,
            Self::UsageForecastDayOther => 92,
            Self::UsagePaceComfortable => 93,
            Self::UsagePaceNormal => 94,
            Self::UsagePaceFast => 95,
            Self::UsagePaceMeasuring => 96,
            Self::UsagePaceUnavailable => 97,
            Self::UsagePaceDisabled => 98,
            Self::UsagePaceRecentActivity => 99,
            Self::UsagePaceExpectedRemaining => 100,
            Self::UsagePaceBeforeReset => 101,
            Self::UpdateInstallPrompt => 102,
            Self::UpdateActionInstall => 103,
            Self::UpdateActionSkipVersion => 104,
            Self::UpdateDownloading => 105,
            Self::UpdateInstalling => 106,
            Self::UpdateDownloadFailed => 107,
            Self::UpdateVerificationFailed => 108,
            Self::UpdateInstallFailed => 109,
            Self::UpdateUnofficialBuildWarning => 110,
        }
    }
}

const LOCALIZATION_KEY_COUNT: usize = 111;

const KOREAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "자동 갱신 중",
    "새로 고치는 중",
    "정보가 오래되었습니다",
    "사용량 정보를 사용할 수 없습니다",
    "갱신",
    "지금 갱신",
    "갱신 간격",
    "Windows 시작 시 실행",
    "시작 화면",
    "위젯 표시",
    "트레이에만 표시",
    "자동 인증 갱신",
    "Codex 로그인",
    "인증 갱신",
    "언어",
    "자동",
    "진단",
    "업데이트 확인",
    "설정",
    "종료",
    "위젯 표시",
    "위젯 숨기기",
    "시작: 위젯 표시",
    "시작: 트레이만",
    "위젯: 모든 모니터",
    "위젯: 주 모니터만",
    "위젯 위치",
    "모든 모니터",
    "주 모니터만",
    "새 업데이트를 사용할 수 있습니다",
    "최신 버전입니다",
    "업데이트를 확인하는 중입니다",
    "업데이트 확인에 실패했습니다",
    "Codex 사용량 모니터",
    "Codex 사용량 모니터 설정",
    "Codex 사용량 모니터 진단",
    "주 사용량 창",
    "보조 사용량 창",
    "Codex CLI를 확인할 수 없습니다",
    "Codex 서비스 요청에 실패했습니다",
    "로그인 상태를 확인할 수 없습니다",
    "설정을 읽거나 검증할 수 없습니다",
    "프록시 사용 여부를 확인했습니다",
    "작업 표시줄 상태를 확인할 수 없습니다",
    "남은 사용량으로 표시",
    "주간 사용량 표시",
    "버전 {version}을 사용할 수 있습니다.\n\nGitHub 릴리스 페이지를 여시겠습니까?",
    "업데이트 확인에 실패했습니다. 네트워크 또는 프록시 설정을 확인한 후 다시 시도하세요.",
    "GitHub 릴리스 페이지를 열 수 없습니다. 기본 브라우저 설정을 확인하세요.",
    "사용량 프로필",
    "사용량 프로필 추가",
    "사용량 프로필 관리",
    "기본 Codex 계정",
    "표시 중",
    "Codex CLI 로그인은 변경되지 않습니다",
    "로그인 필요",
    "사용량 프로필 추가",
    "브라우저에서 사용할 계정을 확인하세요",
    "이름 변경",
    "로그인",
    "로그아웃",
    "삭제",
    "이 사용량 프로필을 삭제할까요?",
    "최대 사용량 프로필 수에 도달했습니다",
    "닫기",
    "프로필 이름",
    "프로필 이름을 확인하세요",
    "Codex CLI와 IDE 로그인은 변경되지 않습니다",
    "로컬 프로필 데이터는 복구할 수 없습니다",
    "프로필 작업을 완료할 수 없습니다",
    "취소",
    "리셋 쿠폰",
    "소모",
    "종료",
    "사용량 소진 예측",
    "사용량 소진 예측",
    "사용량 예측 기록 삭제",
    "사용량 소진 예측 기록을 삭제할까요?",
    "예측 데이터 수집 중 · {count}/{required}",
    "사용량 변화가 적어 소진 시점을 예측할 수 없음",
    "현재 속도면 약 {duration} 후 소진",
    "초기화 전에 소진할 가능성이 높음 · 약 {duration} 후",
    "초기화 시 약 {percent}% 남을 것으로 예상",
    "소진 시점은 7일 이상 후로 예상됨",
    "한도 소진됨",
    "예측 데이터가 오래되어 표시하지 않음",
    "예측 데이터를 사용할 수 없음",
    "분",
    "분",
    "시간",
    "시간",
    "일",
    "일",
    "소비 속도: 여유",
    "소비 속도: 보통",
    "소비 속도: 빠름",
    "소비 속도 측정 중 · 데이터 {count}/{required} · 관측 {minutes}/{required_minutes}분",
    "소비 속도를 판단할 수 없음 · 최신 사용량과 초기화 시각이 필요함",
    "소비 속도 표시 꺼짐",
    "최근 {duration} 동안 {rise}% 사용 · 시간당 약 {rate}%",
    "현재 속도면 초기화 시 약 {percent}% 남아요",
    "현재 속도면 초기화 전에 소진될 수 있어요",
    "CodexPeek {version} 버전이 출시되었습니다.\n\n지금 업데이트할까요? 기존 설정은 그대로 유지됩니다.",
    "지금 업데이트",
    "이번 버전 건너뛰기",
    "업데이트를 다운로드하는 중입니다",
    "업데이트를 설치하고 다시 시작하는 중입니다",
    "업데이트를 다운로드하지 못했습니다. 네트워크 또는 프록시 설정을 확인한 후 다시 시도하세요.",
    "다운로드한 업데이트를 확인할 수 없어 설치하지 않았습니다. GitHub 릴리스 페이지에서 직접 업데이트하세요.",
    "업데이트를 설치하지 못했습니다. CodexPeek를 종료한 뒤 다시 시도하거나 GitHub 릴리스 페이지에서 직접 업데이트하세요.",
    "이 CodexPeek 실행 파일은 공식 GitHub 릴리스 빌드가 아닙니다.\n\n자동 업데이트가 비활성화되었습니다. 공식 릴리스로 교체하면 직접 수정해 빌드한 내용은 포함되지 않습니다. 업데이트하려면 소스를 다시 받아 빌드하거나 공식 릴리스를 수동으로 설치하세요.",
];

const ENGLISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Polling",
    "Refreshing",
    "Usage data is stale",
    "Usage unavailable",
    "Refresh",
    "Refresh now",
    "Refresh interval",
    "Start with Windows",
    "Startup view",
    "Show widget",
    "Tray only",
    "Automatic authentication refresh",
    "Sign in to Codex",
    "Refresh authentication",
    "Language",
    "Automatic",
    "Diagnostics",
    "Check for updates",
    "Settings",
    "Exit",
    "Show widget",
    "Hide widget",
    "Startup: show widget",
    "Startup: tray only",
    "Widget: all monitors",
    "Widget: primary monitor only",
    "Widget placement",
    "All monitors",
    "Primary monitor only",
    "An update is available",
    "You are up to date",
    "Checking for updates",
    "Update check failed",
    "Codex Usage Monitor",
    "Codex Usage Monitor Settings",
    "Codex Usage Monitor Diagnostics",
    "Primary window",
    "Secondary window",
    "Codex CLI could not be verified",
    "Codex service request failed",
    "Login status could not be verified",
    "Settings could not be read or validated",
    "Proxy presence was checked",
    "Taskbar status could not be verified",
    "Show remaining usage",
    "Show weekly usage",
    "Version {version} is available.\n\nOpen the GitHub release page?",
    "The update check failed. Check your network or proxy settings and try again.",
    "The GitHub release page could not be opened. Check your default browser settings.",
    "Usage profiles",
    "Add usage profile",
    "Manage usage profiles",
    "Default Codex account",
    "Displayed",
    "Codex CLI sign-in is unchanged",
    "Sign-in required",
    "Add usage profile",
    "Confirm the account to use in your browser",
    "Rename",
    "Sign in",
    "Sign out",
    "Delete",
    "Delete this usage profile?",
    "The usage profile limit has been reached",
    "Close",
    "Profile name",
    "Check the profile name",
    "Codex CLI and IDE sign-ins are unchanged",
    "local profile data cannot be recovered",
    "The profile operation could not be completed",
    "Cancel",
    "Reset coupons",
    "used",
    "ends",
    "Usage forecasting",
    "Usage forecasting",
    "Clear usage forecast history",
    "Clear the usage forecast history?",
    "Collecting forecast data · {count}/{required}",
    "Usage change is too small to estimate exhaustion",
    "At the current rate, exhaustion in about {duration}",
    "Likely exhausted before reset · in about {duration}",
    "About {percent}% remaining at reset",
    "Exhaustion is estimated to be at least 7 days away",
    "Limit exhausted",
    "Forecast is hidden because the data is stale",
    "Forecast data is unavailable",
    "minute",
    "minutes",
    "hour",
    "hours",
    "day",
    "days",
    "Usage pace: Comfortable",
    "Usage pace: Moderate",
    "Usage pace: Fast",
    "Measuring usage pace · data {count}/{required} · observed {minutes}/{required_minutes} min",
    "Usage pace unavailable · recent usage and a reset time are required",
    "Usage pace display is off",
    "Used {rise}% over the last {duration} · about {rate}% per hour",
    "At this pace, about {percent}% will remain at reset",
    "At this pace, the limit may be exhausted before reset",
    "CodexPeek {version} is available.\n\nUpdate now? Your existing settings will be preserved.",
    "Update now",
    "Skip this version",
    "Downloading update",
    "Installing update and restarting",
    "The update could not be downloaded. Check your network or proxy settings and try again.",
    "The downloaded update could not be verified, so it was not installed. Update manually from the GitHub release page.",
    "The update could not be installed. Close CodexPeek and try again, or update manually from the GitHub release page.",
    "This CodexPeek executable is not an official GitHub release build.\n\nAutomatic updates are disabled. Replacing it with an official release will not include locally built changes. To update, pull and rebuild the source or install an official release manually.",
];

const SPANISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Consultando",
    "Actualizando",
    "Los datos de uso no están actualizados",
    "Uso no disponible",
    "Actualizar",
    "Actualizar ahora",
    "Intervalo de actualización",
    "Iniciar con Windows",
    "Vista inicial",
    "Mostrar widget",
    "Solo bandeja",
    "Actualización automática de autenticación",
    "Iniciar sesión en Codex",
    "Actualizar autenticación",
    "Idioma",
    "Automático",
    "Diagnóstico",
    "Buscar actualizaciones",
    "Configuración",
    "Salir",
    "Mostrar widget",
    "Ocultar widget",
    "Inicio: mostrar widget",
    "Inicio: solo bandeja",
    "Widget: todos los monitores",
    "Widget: solo monitor principal",
    "Ubicación del widget",
    "Todos los monitores",
    "Solo monitor principal",
    "Hay una actualización disponible",
    "Tienes la versión más reciente",
    "Buscando actualizaciones",
    "Error al buscar actualizaciones",
    "Monitor de uso de Codex",
    "Configuración del monitor de uso de Codex",
    "Diagnóstico del monitor de uso de Codex",
    "Ventana principal",
    "Ventana secundaria",
    "No se pudo verificar Codex CLI",
    "Falló la solicitud del servicio Codex",
    "No se pudo verificar el inicio de sesión",
    "No se pudo leer o validar la configuración",
    "Se comprobó la presencia de proxy",
    "No se pudo verificar el estado de la barra de tareas",
    "Mostrar uso restante",
    "Mostrar uso semanal",
    "La versión {version} está disponible.\n\n¿Abrir la página de la versión en GitHub?",
    "La búsqueda de actualizaciones falló. Comprueba la configuración de red o proxy e inténtalo de nuevo.",
    "No se pudo abrir la página de la versión en GitHub. Comprueba la configuración del navegador predeterminado.",
    "Perfiles de uso",
    "Añadir perfil de uso",
    "Administrar perfiles de uso",
    "Cuenta predeterminada de Codex",
    "Mostrado",
    "El inicio de sesión de Codex CLI no cambia",
    "Inicio de sesión necesario",
    "Añadir perfil de uso",
    "Confirma en el navegador la cuenta que quieres usar",
    "Cambiar nombre",
    "Iniciar sesión",
    "Cerrar sesión",
    "Eliminar",
    "¿Eliminar este perfil de uso?",
    "Se alcanzó el límite de perfiles de uso",
    "Cerrar",
    "Nombre del perfil",
    "Comprueba el nombre del perfil",
    "Los inicios de sesión de Codex CLI e IDE no cambian",
    "Los datos locales del perfil no se pueden recuperar",
    "No se pudo completar la operación del perfil",
    "Cancelar",
    "Cupones de reinicio",
    "usado",
    "termina",
    "Predicción de uso",
    "Predicción de uso",
    "Borrar el historial de predicción de uso",
    "¿Borrar el historial de predicción de uso?",
    "Recopilando datos de predicción · {count}/{required}",
    "El cambio de uso es demasiado pequeño para estimar el agotamiento",
    "Al ritmo actual, se agotará en aproximadamente {duration}",
    "Probablemente se agotará antes del reinicio · en aproximadamente {duration}",
    "Aproximadamente {percent}% restante al reiniciarse",
    "Se estima que el agotamiento tardará al menos 7 días",
    "Límite agotado",
    "La predicción está oculta porque los datos son antiguos",
    "Datos de predicción no disponibles",
    "minuto",
    "minutos",
    "hora",
    "horas",
    "día",
    "días",
    "Ritmo de uso: Holgado",
    "Ritmo de uso: Moderado",
    "Ritmo de uso: Rápido",
    "Midiendo el ritmo de uso · datos {count}/{required} · observación {minutes}/{required_minutes} min",
    "Ritmo de uso no disponible · se requieren datos recientes y una hora de restablecimiento",
    "La visualización del ritmo de uso está desactivada",
    "Uso del {rise}% en las últimas {duration} · aprox. {rate}% por hora",
    "A este ritmo, quedará cerca del {percent}% al restablecerse",
    "A este ritmo, el límite puede agotarse antes del restablecimiento",
    "CodexPeek {version} está disponible.\n\n¿Actualizar ahora? Se conservará tu configuración.",
    "Actualizar ahora",
    "Omitir esta versión",
    "Descargando actualización",
    "Instalando la actualización y reiniciando",
    "No se pudo descargar la actualización. Comprueba la red o la configuración del proxy e inténtalo de nuevo.",
    "No se pudo verificar la actualización descargada, por lo que no se instaló. Actualiza manualmente desde la página de versiones de GitHub.",
    "No se pudo instalar la actualización. Cierra CodexPeek e inténtalo de nuevo, o actualiza manualmente desde la página de versiones de GitHub.",
    "Este ejecutable de CodexPeek no es una compilación oficial de GitHub.\n\nLas actualizaciones automáticas están desactivadas. Al reemplazarlo por una versión oficial no se incluirán los cambios compilados localmente. Para actualizar, descarga y recompila el código fuente o instala manualmente una versión oficial.",
];

const PORTUGUESE_BRAZIL_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Consultando",
    "Atualizando",
    "Os dados de uso estão desatualizados",
    "Uso indisponível",
    "Atualizar",
    "Atualizar agora",
    "Intervalo de atualização",
    "Iniciar com Windows",
    "Tela inicial",
    "Mostrar widget",
    "Somente bandeja",
    "Atualização automática da autenticação",
    "Entrar no Codex",
    "Atualizar autenticação",
    "Idioma",
    "Automático",
    "Diagnóstico",
    "Verificar atualizações",
    "Configurações",
    "Sair",
    "Mostrar widget",
    "Ocultar widget",
    "Inicialização: mostrar widget",
    "Inicialização: somente bandeja",
    "Widget: todos os monitores",
    "Widget: somente monitor principal",
    "Posição do widget",
    "Todos os monitores",
    "Somente monitor principal",
    "Há uma atualização disponível",
    "Você está na versão mais recente",
    "Verificando atualizações",
    "Falha ao verificar atualizações",
    "Monitor de uso do Codex",
    "Configurações do monitor de uso do Codex",
    "Diagnóstico do monitor de uso do Codex",
    "Janela principal",
    "Janela secundária",
    "Não foi possível verificar o Codex CLI",
    "Falha na solicitação do serviço Codex",
    "Não foi possível verificar o login",
    "Não foi possível ler ou validar as configurações",
    "A presença de proxy foi verificada",
    "Não foi possível verificar o status da barra de tarefas",
    "Mostrar uso restante",
    "Mostrar uso semanal",
    "A versão {version} está disponível.\n\nAbrir a página da versão no GitHub?",
    "A verificação de atualizações falhou. Verifique as configurações de rede ou proxy e tente novamente.",
    "Não foi possível abrir a página da versão no GitHub. Verifique as configurações do navegador padrão.",
    "Perfis de uso",
    "Adicionar perfil de uso",
    "Gerenciar perfis de uso",
    "Conta padrão do Codex",
    "Exibido",
    "O login do Codex CLI não é alterado",
    "Login necessário",
    "Adicionar perfil de uso",
    "Confirme no navegador a conta que deseja usar",
    "Renomear",
    "Entrar",
    "Sair",
    "Excluir",
    "Excluir este perfil de uso?",
    "O limite de perfis de uso foi atingido",
    "Fechar",
    "Nome do perfil",
    "Verifique o nome do perfil",
    "Os logins do Codex CLI e da IDE não são alterados",
    "Os dados locais do perfil não podem ser recuperados",
    "Não foi possível concluir a operação do perfil",
    "Cancelar",
    "Cupons de redefinição",
    "usado",
    "termina",
    "Previsão de uso",
    "Previsão de uso",
    "Limpar histórico de previsão de uso",
    "Limpar o histórico de previsão de uso?",
    "Coletando dados de previsão · {count}/{required}",
    "A mudança de uso é pequena demais para estimar o esgotamento",
    "No ritmo atual, o limite acaba em cerca de {duration}",
    "Provavelmente esgotará antes da redefinição · em cerca de {duration}",
    "Cerca de {percent}% restantes na redefinição",
    "O esgotamento é estimado para daqui a pelo menos 7 dias",
    "Limite esgotado",
    "A previsão está oculta porque os dados estão desatualizados",
    "Dados de previsão indisponíveis",
    "minuto",
    "minutos",
    "hora",
    "horas",
    "dia",
    "dias",
    "Ritmo de uso: Tranquilo",
    "Ritmo de uso: Moderado",
    "Ritmo de uso: Rápido",
    "Medindo o ritmo de uso · dados {count}/{required} · observação {minutes}/{required_minutes} min",
    "Ritmo de uso indisponível · são necessários dados recentes e um horário de redefinição",
    "A exibição do ritmo de uso está desativada",
    "Uso de {rise}% nas últimas {duration} · cerca de {rate}% por hora",
    "Neste ritmo, cerca de {percent}% restará na redefinição",
    "Neste ritmo, o limite pode se esgotar antes da redefinição",
    "CodexPeek {version} está disponível.\n\nAtualizar agora? Suas configurações serão mantidas.",
    "Atualizar agora",
    "Ignorar esta versão",
    "Baixando atualização",
    "Instalando a atualização e reiniciando",
    "Não foi possível baixar a atualização. Verifique a rede ou as configurações de proxy e tente novamente.",
    "Não foi possível verificar a atualização baixada, então ela não foi instalada. Atualize manualmente pela página de lançamentos do GitHub.",
    "Não foi possível instalar a atualização. Feche o CodexPeek e tente novamente ou atualize manualmente pela página de lançamentos do GitHub.",
    "Este executável do CodexPeek não é uma compilação oficial do GitHub.\n\nAs atualizações automáticas estão desativadas. A substituição por uma versão oficial não incluirá alterações compiladas localmente. Para atualizar, baixe e compile novamente o código-fonte ou instale uma versão oficial manualmente.",
];

const INDONESIAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Memeriksa",
    "Menyegarkan",
    "Data penggunaan sudah lama",
    "Penggunaan tidak tersedia",
    "Segarkan",
    "Segarkan sekarang",
    "Interval penyegaran",
    "Mulai bersama Windows",
    "Tampilan awal",
    "Tampilkan widget",
    "Hanya baki sistem",
    "Penyegaran autentikasi otomatis",
    "Masuk ke Codex",
    "Segarkan autentikasi",
    "Bahasa",
    "Otomatis",
    "Diagnostik",
    "Periksa pembaruan",
    "Pengaturan",
    "Keluar",
    "Tampilkan widget",
    "Sembunyikan widget",
    "Awal: tampilkan widget",
    "Awal: hanya baki sistem",
    "Widget: semua monitor",
    "Widget: hanya monitor utama",
    "Posisi widget",
    "Semua monitor",
    "Hanya monitor utama",
    "Pembaruan tersedia",
    "Anda sudah menggunakan versi terbaru",
    "Memeriksa pembaruan",
    "Pemeriksaan pembaruan gagal",
    "Monitor Penggunaan Codex",
    "Pengaturan Monitor Penggunaan Codex",
    "Diagnostik Monitor Penggunaan Codex",
    "Jendela utama",
    "Jendela sekunder",
    "Codex CLI tidak dapat diverifikasi",
    "Permintaan layanan Codex gagal",
    "Status login tidak dapat diverifikasi",
    "Pengaturan tidak dapat dibaca atau divalidasi",
    "Keberadaan proxy telah diperiksa",
    "Status taskbar tidak dapat diverifikasi",
    "Tampilkan sisa penggunaan",
    "Tampilkan penggunaan mingguan",
    "Versi {version} tersedia.\n\nBuka halaman rilis GitHub?",
    "Pemeriksaan pembaruan gagal. Periksa pengaturan jaringan atau proksi, lalu coba lagi.",
    "Halaman rilis GitHub tidak dapat dibuka. Periksa pengaturan browser default.",
    "Profil penggunaan",
    "Tambah profil penggunaan",
    "Kelola profil penggunaan",
    "Akun Codex default",
    "Ditampilkan",
    "Login Codex CLI tidak berubah",
    "Perlu login",
    "Tambah profil penggunaan",
    "Konfirmasikan akun yang akan digunakan di browser",
    "Ganti nama",
    "Masuk",
    "Keluar",
    "Hapus",
    "Hapus profil penggunaan ini?",
    "Batas profil penggunaan telah tercapai",
    "Tutup",
    "Nama profil",
    "Periksa nama profil",
    "Login Codex CLI dan IDE tidak berubah",
    "Data profil lokal tidak dapat dipulihkan",
    "Operasi profil tidak dapat diselesaikan",
    "Batal",
    "Kupon reset",
    "digunakan",
    "berakhir",
    "Prediksi penggunaan",
    "Prediksi penggunaan",
    "Hapus riwayat prediksi penggunaan",
    "Hapus riwayat prediksi penggunaan?",
    "Mengumpulkan data prediksi · {count}/{required}",
    "Perubahan penggunaan terlalu kecil untuk memperkirakan habisnya batas",
    "Dengan laju saat ini, habis dalam sekitar {duration}",
    "Kemungkinan habis sebelum reset · sekitar {duration} lagi",
    "Sekitar {percent}% tersisa saat reset",
    "Kehabisan diperkirakan setidaknya 7 hari lagi",
    "Batas habis",
    "Prediksi disembunyikan karena data sudah lama",
    "Data prediksi tidak tersedia",
    "menit",
    "menit",
    "jam",
    "jam",
    "hari",
    "hari",
    "Laju penggunaan: Longgar",
    "Laju penggunaan: Sedang",
    "Laju penggunaan: Cepat",
    "Mengukur laju penggunaan · data {count}/{required} · diamati {minutes}/{required_minutes} mnt",
    "Laju penggunaan tidak tersedia · penggunaan terbaru dan waktu reset diperlukan",
    "Tampilan laju penggunaan nonaktif",
    "Menggunakan {rise}% selama {duration} terakhir · sekitar {rate}% per jam",
    "Dengan laju ini, sekitar {percent}% akan tersisa saat reset",
    "Dengan laju ini, batas dapat habis sebelum reset",
    "CodexPeek {version} tersedia.\n\nPerbarui sekarang? Pengaturan Anda akan tetap dipertahankan.",
    "Perbarui sekarang",
    "Lewati versi ini",
    "Mengunduh pembaruan",
    "Menginstal pembaruan dan memulai ulang",
    "Pembaruan tidak dapat diunduh. Periksa pengaturan jaringan atau proksi, lalu coba lagi.",
    "Pembaruan yang diunduh tidak dapat diverifikasi sehingga tidak diinstal. Perbarui secara manual dari halaman rilis GitHub.",
    "Pembaruan tidak dapat diinstal. Tutup CodexPeek lalu coba lagi, atau perbarui secara manual dari halaman rilis GitHub.",
    "Executable CodexPeek ini bukan build rilis GitHub resmi.\n\nPembaruan otomatis dinonaktifkan. Menggantinya dengan rilis resmi tidak akan menyertakan perubahan yang dibuat dalam build lokal. Untuk memperbarui, tarik dan build ulang kode sumber atau instal rilis resmi secara manual.",
];

const JAPANESE_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "自動更新中",
    "更新中",
    "使用量データが古くなっています",
    "使用量を利用できません",
    "更新",
    "今すぐ更新",
    "更新間隔",
    "Windows 起動時に実行",
    "起動時の表示",
    "ウィジェットを表示",
    "トレイのみ",
    "認証の自動更新",
    "Codex にログイン",
    "認証を更新",
    "言語",
    "自動",
    "診断",
    "更新を確認",
    "設定",
    "終了",
    "ウィジェットを表示",
    "ウィジェットを隠す",
    "起動: ウィジェットを表示",
    "起動: トレイのみ",
    "ウィジェット: すべてのモニター",
    "ウィジェット: メインモニターのみ",
    "ウィジェットの配置",
    "すべてのモニター",
    "メインモニターのみ",
    "新しい更新があります",
    "最新バージョンです",
    "更新を確認中",
    "更新の確認に失敗しました",
    "Codex 使用量モニター",
    "Codex 使用量モニター設定",
    "Codex 使用量モニター診断",
    "メインウィンドウ",
    "サブウィンドウ",
    "Codex CLI を確認できませんでした",
    "Codex サービス要求に失敗しました",
    "ログイン状態を確認できませんでした",
    "設定を読み取りまたは検証できませんでした",
    "プロキシの有無を確認しました",
    "タスクバーの状態を確認できませんでした",
    "残り使用量を表示",
    "週間使用量を表示",
    "バージョン {version} を利用できます。\n\nGitHub のリリースページを開きますか？",
    "更新の確認に失敗しました。ネットワークまたはプロキシ設定を確認して、もう一度お試しください。",
    "GitHub のリリースページを開けませんでした。既定のブラウザー設定を確認してください。",
    "使用量プロファイル",
    "使用量プロファイルを追加",
    "使用量プロファイルを管理",
    "デフォルトの Codex アカウント",
    "表示中",
    "Codex CLI のサインインは変更されません",
    "サインインが必要です",
    "使用量プロファイルを追加",
    "ブラウザーで使用するアカウントを確認してください",
    "名前を変更",
    "サインイン",
    "サインアウト",
    "削除",
    "この使用量プロファイルを削除しますか？",
    "使用量プロファイルの上限に達しました",
    "閉じる",
    "プロファイル名",
    "プロファイル名を確認してください",
    "Codex CLI と IDE のサインインは変更されません",
    "ローカルプロファイルデータは復元できません",
    "プロファイル操作を完了できませんでした",
    "キャンセル",
    "リセットクーポン",
    "使用済み",
    "終了",
    "使用量の予測",
    "使用量の予測",
    "使用量予測の履歴を消去",
    "使用量予測の履歴を消去しますか？",
    "予測データを収集中 · {count}/{required}",
    "使用量の変化が小さいため消尽時刻を予測できません",
    "現在の速度では約{duration}後に上限に達します",
    "リセット前に上限に達する可能性が高い · 約{duration}後",
    "リセット時の残りは約{percent}%と予測",
    "上限に達するのは7日以上先と予測",
    "上限に達しました",
    "データが古いため予測を非表示",
    "予測データを利用できません",
    "分",
    "分",
    "時間",
    "時間",
    "日",
    "日",
    "消費ペース: 余裕",
    "消費ペース: 標準",
    "消費ペース: 速い",
    "消費ペースを測定中 · データ {count}/{required} · 観測 {minutes}/{required_minutes}分",
    "消費ペースを判定できません · 最新の使用量とリセット時刻が必要です",
    "消費ペース表示はオフ",
    "直近{duration}で{rise}%使用 · 1時間あたり約{rate}%",
    "このペースではリセット時に約{percent}%残ります",
    "このペースではリセット前に上限へ達する可能性があります",
    "CodexPeek {version} を利用できます。\n\n今すぐ更新しますか？設定は保持されます。",
    "今すぐ更新",
    "このバージョンをスキップ",
    "更新をダウンロードしています",
    "更新をインストールして再起動しています",
    "更新をダウンロードできませんでした。ネットワークまたはプロキシ設定を確認して、もう一度お試しください。",
    "ダウンロードした更新を確認できなかったため、インストールしませんでした。GitHub のリリースページから手動で更新してください。",
    "更新をインストールできませんでした。CodexPeek を終了してもう一度試すか、GitHub のリリースページから手動で更新してください。",
    "この CodexPeek 実行ファイルは、GitHub の公式リリースビルドではありません。\n\n自動更新は無効です。公式リリースに置き換えると、ローカルでビルドした変更は含まれません。更新するには、ソースを取得して再ビルドするか、公式リリースを手動でインストールしてください。",
];

const HINDI_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "पोलिंग",
    "रीफ़्रेश हो रहा है",
    "उपयोग डेटा पुराना है",
    "उपयोग उपलब्ध नहीं",
    "रीफ़्रेश",
    "अभी रीफ़्रेश करें",
    "रीफ़्रेश अंतराल",
    "Windows के साथ शुरू करें",
    "स्टार्टअप दृश्य",
    "विजेट दिखाएँ",
    "केवल ट्रे",
    "स्वचालित प्रमाणीकरण रीफ़्रेश",
    "Codex में साइन इन करें",
    "प्रमाणीकरण रीफ़्रेश करें",
    "भाषा",
    "स्वतः",
    "निदान",
    "अपडेट जाँचें",
    "सेटिंग्स",
    "बाहर निकलें",
    "विजेट दिखाएँ",
    "विजेट छिपाएँ",
    "स्टार्टअप: विजेट दिखाएँ",
    "स्टार्टअप: केवल ट्रे",
    "विजेट: सभी मॉनिटर",
    "विजेट: केवल मुख्य मॉनिटर",
    "विजेट स्थान",
    "सभी मॉनिटर",
    "केवल मुख्य मॉनिटर",
    "अपडेट उपलब्ध है",
    "आप नवीनतम संस्करण पर हैं",
    "अपडेट जाँचे जा रहे हैं",
    "अपडेट जाँच विफल रही",
    "Codex उपयोग मॉनिटर",
    "Codex उपयोग मॉनिटर सेटिंग्स",
    "Codex उपयोग मॉनिटर निदान",
    "मुख्य विंडो",
    "द्वितीयक विंडो",
    "Codex CLI सत्यापित नहीं हो सका",
    "Codex सेवा अनुरोध विफल रहा",
    "लॉगिन स्थिति सत्यापित नहीं हो सकी",
    "सेटिंग्स पढ़ी या सत्यापित नहीं की जा सकीं",
    "प्रॉक्सी की उपस्थिति जाँची गई",
    "टास्कबार स्थिति सत्यापित नहीं हो सकी",
    "शेष उपयोग दिखाएँ",
    "साप्ताहिक उपयोग दिखाएँ",
    "संस्करण {version} उपलब्ध है।\n\nGitHub रिलीज़ पृष्ठ खोलें?",
    "अपडेट जाँच विफल रही। नेटवर्क या प्रॉक्सी सेटिंग जाँचें और फिर से प्रयास करें।",
    "GitHub रिलीज़ पृष्ठ नहीं खुल सका। डिफ़ॉल्ट ब्राउज़र सेटिंग जाँचें।",
    "उपयोग प्रोफ़ाइल",
    "उपयोग प्रोफ़ाइल जोड़ें",
    "उपयोग प्रोफ़ाइल प्रबंधित करें",
    "डिफ़ॉल्ट Codex खाता",
    "प्रदर्शित",
    "Codex CLI साइन-इन अपरिवर्तित रहता है",
    "साइन-इन आवश्यक",
    "उपयोग प्रोफ़ाइल जोड़ें",
    "ब्राउज़र में उपयोग करने वाला खाता सुनिश्चित करें",
    "नाम बदलें",
    "साइन इन करें",
    "साइन आउट करें",
    "हटाएँ",
    "यह उपयोग प्रोफ़ाइल हटाएँ?",
    "उपयोग प्रोफ़ाइल की सीमा पूरी हो गई है",
    "बंद करें",
    "प्रोफ़ाइल का नाम",
    "प्रोफ़ाइल का नाम जाँचें",
    "Codex CLI और IDE साइन-इन अपरिवर्तित रहते हैं",
    "स्थानीय प्रोफ़ाइल डेटा पुनर्प्राप्त नहीं किया जा सकता",
    "प्रोफ़ाइल कार्रवाई पूरी नहीं हो सकी",
    "रद्द करें",
    "रीसेट कूपन",
    "उपयोग किया गया",
    "समाप्त",
    "उपयोग पूर्वानुमान",
    "उपयोग पूर्वानुमान",
    "उपयोग पूर्वानुमान इतिहास साफ़ करें",
    "उपयोग पूर्वानुमान इतिहास साफ़ करें?",
    "पूर्वानुमान डेटा एकत्रित हो रहा है · {count}/{required}",
    "उपयोग में बदलाव बहुत कम है, समाप्ति का अनुमान नहीं लगाया जा सकता",
    "वर्तमान दर पर लगभग {duration} में सीमा समाप्त होगी",
    "रीसेट से पहले समाप्त होने की संभावना अधिक · लगभग {duration} में",
    "रीसेट पर लगभग {percent}% शेष रहने का अनुमान",
    "समाप्ति का अनुमान कम से कम 7 दिन बाद है",
    "सीमा समाप्त",
    "पुराने डेटा के कारण पूर्वानुमान छिपाया गया",
    "पूर्वानुमान डेटा उपलब्ध नहीं है",
    "मिनट",
    "मिनट",
    "घंटा",
    "घंटे",
    "दिन",
    "दिन",
    "उपयोग गति: सहज",
    "उपयोग गति: सामान्य",
    "उपयोग गति: तेज़",
    "उपयोग गति मापी जा रही है · डेटा {count}/{required} · अवलोकन {minutes}/{required_minutes} मिनट",
    "उपयोग गति उपलब्ध नहीं · हाल का उपयोग और रीसेट समय आवश्यक है",
    "उपयोग गति प्रदर्शन बंद है",
    "पिछले {duration} में {rise}% उपयोग · लगभग {rate}% प्रति घंटा",
    "इस गति पर रीसेट के समय लगभग {percent}% शेष रहेगा",
    "इस गति पर सीमा रीसेट से पहले समाप्त हो सकती है",
    "CodexPeek {version} उपलब्ध है।\n\nअभी अपडेट करें? आपकी सेटिंग्स सुरक्षित रहेंगी।",
    "अभी अपडेट करें",
    "इस संस्करण को छोड़ें",
    "अपडेट डाउनलोड हो रहा है",
    "अपडेट इंस्टॉल करके पुनः शुरू किया जा रहा है",
    "अपडेट डाउनलोड नहीं हो सका। अपना नेटवर्क या प्रॉक्सी सेटिंग जाँचें और फिर प्रयास करें।",
    "डाउनलोड किए गए अपडेट को सत्यापित नहीं किया जा सका, इसलिए उसे इंस्टॉल नहीं किया गया। GitHub रिलीज़ पेज से मैन्युअल रूप से अपडेट करें।",
    "अपडेट इंस्टॉल नहीं किया जा सका। CodexPeek बंद करके फिर प्रयास करें, या GitHub रिलीज़ पेज से मैन्युअल रूप से अपडेट करें।",
    "यह CodexPeek निष्पादन योग्य फ़ाइल आधिकारिक GitHub रिलीज़ बिल्ड नहीं है।\n\nस्वचालित अपडेट अक्षम हैं। इसे आधिकारिक रिलीज़ से बदलने पर स्थानीय रूप से बनाए गए बदलाव शामिल नहीं होंगे। अपडेट करने के लिए स्रोत खींचकर फिर से बिल्ड करें या आधिकारिक रिलीज़ मैन्युअल रूप से इंस्टॉल करें।",
];

const GERMAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Abfrage läuft",
    "Aktualisieren",
    "Nutzungsdaten sind veraltet",
    "Nutzung nicht verfügbar",
    "Aktualisieren",
    "Jetzt aktualisieren",
    "Aktualisierungsintervall",
    "Mit Windows starten",
    "Startansicht",
    "Widget anzeigen",
    "Nur Infobereich",
    "Automatische Authentifizierung aktualisieren",
    "Bei Codex anmelden",
    "Authentifizierung aktualisieren",
    "Sprache",
    "Automatisch",
    "Diagnose",
    "Nach Updates suchen",
    "Einstellungen",
    "Beenden",
    "Widget anzeigen",
    "Widget ausblenden",
    "Start: Widget anzeigen",
    "Start: nur Infobereich",
    "Widget: alle Monitore",
    "Widget: nur Hauptmonitor",
    "Widget-Position",
    "Alle Monitore",
    "Nur Hauptmonitor",
    "Ein Update ist verfügbar",
    "Sie sind auf dem neuesten Stand",
    "Updates werden gesucht",
    "Updateprüfung fehlgeschlagen",
    "Codex-Nutzungsmonitor",
    "Einstellungen für Codex-Nutzungsmonitor",
    "Diagnose des Codex-Nutzungsmonitors",
    "Hauptfenster",
    "Nebenfenster",
    "Codex CLI konnte nicht verifiziert werden",
    "Codex-Dienstanforderung fehlgeschlagen",
    "Anmeldestatus konnte nicht verifiziert werden",
    "Einstellungen konnten nicht gelesen oder validiert werden",
    "Proxy-Präsenz wurde geprüft",
    "Taskleistenstatus konnte nicht verifiziert werden",
    "Verbleibende Nutzung anzeigen",
    "Wöchentliche Nutzung anzeigen",
    "Version {version} ist verfügbar.\n\nGitHub-Release-Seite öffnen?",
    "Die Updateprüfung ist fehlgeschlagen. Prüfen Sie die Netzwerk- oder Proxy-Einstellungen und versuchen Sie es erneut.",
    "Die GitHub-Release-Seite konnte nicht geöffnet werden. Prüfen Sie die Einstellungen des Standardbrowsers.",
    "Nutzungsprofile",
    "Nutzungsprofil hinzufügen",
    "Nutzungsprofile verwalten",
    "Standard-Codex-Konto",
    "Angezeigt",
    "Die Codex-CLI-Anmeldung bleibt unverändert",
    "Anmeldung erforderlich",
    "Nutzungsprofil hinzufügen",
    "Bestätigen Sie im Browser das zu verwendende Konto",
    "Umbenennen",
    "Anmelden",
    "Abmelden",
    "Löschen",
    "Dieses Nutzungsprofil löschen?",
    "Das Limit für Nutzungsprofile ist erreicht",
    "Schließen",
    "Profilname",
    "Überprüfen Sie den Profilnamen",
    "Codex-CLI- und IDE-Anmeldungen bleiben unverändert",
    "Lokale Profildaten können nicht wiederhergestellt werden",
    "Der Profilvorgang konnte nicht abgeschlossen werden",
    "Abbrechen",
    "Zurücksetzungsgutscheine",
    "verwendet",
    "endet",
    "Nutzungsprognose",
    "Nutzungsprognose",
    "Nutzungsprognoseverlauf löschen",
    "Nutzungsprognoseverlauf löschen?",
    "Prognosedaten werden gesammelt · {count}/{required}",
    "Die Nutzungsänderung ist zu gering für eine Erschöpfungsprognose",
    "Bei der aktuellen Rate ist das Limit in etwa {duration} erschöpft",
    "Wahrscheinlich vor dem Zurücksetzen erschöpft · in etwa {duration}",
    "Beim Zurücksetzen verbleiben voraussichtlich etwa {percent}%",
    "Die Erschöpfung wird frühestens in 7 Tagen erwartet",
    "Limit erschöpft",
    "Prognose wegen veralteter Daten ausgeblendet",
    "Prognosedaten nicht verfügbar",
    "Minute",
    "Minuten",
    "Stunde",
    "Stunden",
    "Tag",
    "Tagen",
    "Nutzungstempo: Entspannt",
    "Nutzungstempo: Normal",
    "Nutzungstempo: Schnell",
    "Nutzungstempo wird gemessen · Daten {count}/{required} · Beobachtung {minutes}/{required_minutes} Min.",
    "Nutzungstempo nicht verfügbar · aktuelle Nutzung und Rücksetzzeit erforderlich",
    "Anzeige des Nutzungstempos ist aus",
    "In den letzten {duration} {rise}% genutzt · etwa {rate}% pro Stunde",
    "Bei diesem Tempo bleiben beim Zurücksetzen etwa {percent}% übrig",
    "Bei diesem Tempo kann das Limit vor dem Zurücksetzen aufgebraucht sein",
    "CodexPeek {version} ist verfügbar.\n\nJetzt aktualisieren? Deine Einstellungen bleiben erhalten.",
    "Jetzt aktualisieren",
    "Diese Version überspringen",
    "Update wird heruntergeladen",
    "Update wird installiert und CodexPeek neu gestartet",
    "Das Update konnte nicht heruntergeladen werden. Prüfe die Netzwerk- oder Proxyeinstellungen und versuche es erneut.",
    "Das heruntergeladene Update konnte nicht überprüft werden und wurde daher nicht installiert. Aktualisiere manuell über die GitHub-Release-Seite.",
    "Das Update konnte nicht installiert werden. Beende CodexPeek und versuche es erneut oder aktualisiere manuell über die GitHub-Release-Seite.",
    "Diese CodexPeek-Datei ist kein offizieller GitHub-Release-Build.\n\nAutomatische Updates sind deaktiviert. Beim Ersetzen durch ein offizielles Release werden lokal erstellte Änderungen nicht übernommen. Aktualisiere den Quellcode und erstelle ihn neu oder installiere ein offizielles Release manuell.",
];

const FRENCH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Interrogation",
    "Actualisation",
    "Les données d'utilisation sont obsolètes",
    "Utilisation indisponible",
    "Actualiser",
    "Actualiser maintenant",
    "Intervalle d'actualisation",
    "Démarrer avec Windows",
    "Vue au démarrage",
    "Afficher le widget",
    "Zone de notification seule",
    "Actualisation automatique de l'authentification",
    "Se connecter à Codex",
    "Actualiser l'authentification",
    "Langue",
    "Automatique",
    "Diagnostics",
    "Rechercher des mises à jour",
    "Paramètres",
    "Quitter",
    "Afficher le widget",
    "Masquer le widget",
    "Démarrage: afficher le widget",
    "Démarrage: zone de notification seule",
    "Widget: tous les moniteurs",
    "Widget: moniteur principal seul",
    "Emplacement du widget",
    "Tous les moniteurs",
    "Moniteur principal seul",
    "Une mise à jour est disponible",
    "Vous êtes à jour",
    "Recherche de mises à jour",
    "Échec de la recherche de mises à jour",
    "Moniteur d'utilisation Codex",
    "Paramètres du moniteur d'utilisation Codex",
    "Diagnostics du moniteur d'utilisation Codex",
    "Fenêtre principale",
    "Fenêtre secondaire",
    "Codex CLI n'a pas pu être vérifié",
    "La requête du service Codex a échoué",
    "L'état de connexion n'a pas pu être vérifié",
    "Les paramètres n'ont pas pu être lus ou validés",
    "La présence d'un proxy a été vérifiée",
    "L'état de la barre des tâches n'a pas pu être vérifié",
    "Afficher l'utilisation restante",
    "Afficher l'utilisation hebdomadaire",
    "La version {version} est disponible.\n\nOuvrir la page de version GitHub ?",
    "La recherche de mises à jour a échoué. Vérifiez les paramètres réseau ou proxy, puis réessayez.",
    "Impossible d'ouvrir la page de version GitHub. Vérifiez les paramètres du navigateur par défaut.",
    "Profils d'utilisation",
    "Ajouter un profil d'utilisation",
    "Gérer les profils d'utilisation",
    "Compte Codex par défaut",
    "Affiché",
    "La connexion à Codex CLI reste inchangée",
    "Connexion requise",
    "Ajouter un profil d'utilisation",
    "Confirmez dans le navigateur le compte à utiliser",
    "Renommer",
    "Se connecter",
    "Se déconnecter",
    "Supprimer",
    "Supprimer ce profil d'utilisation ?",
    "La limite de profils d'utilisation est atteinte",
    "Fermer",
    "Nom du profil",
    "Vérifiez le nom du profil",
    "Les connexions à Codex CLI et à l'IDE restent inchangées",
    "Les données locales du profil sont irrécupérables",
    "L'opération de profil n'a pas pu être effectuée",
    "Annuler",
    "Coupons de réinitialisation",
    "utilisé",
    "se termine",
    "Prévision d'utilisation",
    "Prévision d'utilisation",
    "Effacer l'historique des prévisions d'utilisation",
    "Effacer l'historique des prévisions d'utilisation ?",
    "Collecte des données de prévision · {count}/{required}",
    "La variation d'utilisation est trop faible pour estimer l'épuisement",
    "Au rythme actuel, épuisement dans environ {duration}",
    "Épuisement probable avant la réinitialisation · dans environ {duration}",
    "Environ {percent}% restants lors de la réinitialisation",
    "L'épuisement est prévu dans au moins 7 jours",
    "Limite épuisée",
    "Prévision masquée car les données sont obsolètes",
    "Données de prévision indisponibles",
    "minute",
    "minutes",
    "heure",
    "heures",
    "jour",
    "jours",
    "Rythme d’utilisation : confortable",
    "Rythme d’utilisation : modéré",
    "Rythme d’utilisation : rapide",
    "Mesure du rythme d’utilisation · données {count}/{required} · observation {minutes}/{required_minutes} min",
    "Rythme d’utilisation indisponible · utilisation récente et heure de réinitialisation requises",
    "L’affichage du rythme d’utilisation est désactivé",
    "{rise}% utilisés au cours des dernières {duration} · environ {rate}% par heure",
    "À ce rythme, il restera environ {percent}% à la réinitialisation",
    "À ce rythme, la limite peut être épuisée avant la réinitialisation",
    "CodexPeek {version} est disponible.\n\nMettre à jour maintenant ? Vos paramètres seront conservés.",
    "Mettre à jour",
    "Ignorer cette version",
    "Téléchargement de la mise à jour",
    "Installation de la mise à jour et redémarrage",
    "Impossible de télécharger la mise à jour. Vérifiez les paramètres réseau ou du proxy, puis réessayez.",
    "La mise à jour téléchargée n’a pas pu être vérifiée et n’a donc pas été installée. Effectuez la mise à jour manuellement depuis la page des versions GitHub.",
    "Impossible d’installer la mise à jour. Fermez CodexPeek et réessayez, ou effectuez la mise à jour manuellement depuis la page des versions GitHub.",
    "Cet exécutable CodexPeek n’est pas une version officielle publiée sur GitHub.\n\nLes mises à jour automatiques sont désactivées. Le remplacer par une version officielle n’inclura pas les modifications compilées localement. Pour mettre à jour, récupérez et recompilez le code source ou installez manuellement une version officielle.",
];

const VIETNAMESE_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Đang thăm dò",
    "Đang làm mới",
    "Dữ liệu sử dụng đã cũ",
    "Không có thông tin sử dụng",
    "Làm mới",
    "Làm mới ngay",
    "Khoảng thời gian làm mới",
    "Khởi động cùng Windows",
    "Màn hình khởi động",
    "Hiển thị widget",
    "Chỉ khay hệ thống",
    "Tự động làm mới xác thực",
    "Đăng nhập vào Codex",
    "Làm mới xác thực",
    "Ngôn ngữ",
    "Tự động",
    "Chẩn đoán",
    "Kiểm tra cập nhật",
    "Cài đặt",
    "Thoát",
    "Hiển thị widget",
    "Ẩn widget",
    "Khởi động: hiển thị widget",
    "Khởi động: chỉ khay hệ thống",
    "Widget: tất cả màn hình",
    "Widget: chỉ màn hình chính",
    "Vị trí widget",
    "Tất cả màn hình",
    "Chỉ màn hình chính",
    "Có bản cập nhật mới",
    "Bạn đang dùng phiên bản mới nhất",
    "Đang kiểm tra cập nhật",
    "Kiểm tra cập nhật thất bại",
    "Bộ theo dõi sử dụng Codex",
    "Cài đặt bộ theo dõi sử dụng Codex",
    "Chẩn đoán bộ theo dõi sử dụng Codex",
    "Cửa sổ chính",
    "Cửa sổ phụ",
    "Không thể xác minh Codex CLI",
    "Yêu cầu dịch vụ Codex thất bại",
    "Không thể xác minh trạng thái đăng nhập",
    "Không thể đọc hoặc xác thực cài đặt",
    "Đã kiểm tra sự hiện diện của proxy",
    "Không thể xác minh trạng thái thanh tác vụ",
    "Hiển thị mức sử dụng còn lại",
    "Hiển thị mức sử dụng hằng tuần",
    "Phiên bản {version} hiện có.\n\nMở trang bản phát hành GitHub?",
    "Kiểm tra cập nhật không thành công. Hãy kiểm tra cài đặt mạng hoặc proxy rồi thử lại.",
    "Không thể mở trang bản phát hành GitHub. Hãy kiểm tra cài đặt trình duyệt mặc định.",
    "Hồ sơ sử dụng",
    "Thêm hồ sơ sử dụng",
    "Quản lý hồ sơ sử dụng",
    "Tài khoản Codex mặc định",
    "Đang hiển thị",
    "Đăng nhập Codex CLI không thay đổi",
    "Cần đăng nhập",
    "Thêm hồ sơ sử dụng",
    "Xác nhận tài khoản sẽ dùng trong trình duyệt",
    "Đổi tên",
    "Đăng nhập",
    "Đăng xuất",
    "Xóa",
    "Xóa hồ sơ sử dụng này?",
    "Đã đạt giới hạn hồ sơ sử dụng",
    "Đóng",
    "Tên hồ sơ",
    "Kiểm tra tên hồ sơ",
    "Đăng nhập Codex CLI và IDE không thay đổi",
    "Không thể khôi phục dữ liệu hồ sơ cục bộ",
    "Không thể hoàn tất thao tác hồ sơ",
    "Hủy",
    "Phiếu đặt lại",
    "đã dùng",
    "kết thúc",
    "Dự báo sử dụng",
    "Dự báo sử dụng",
    "Xóa lịch sử dự báo sử dụng",
    "Xóa lịch sử dự báo sử dụng?",
    "Đang thu thập dữ liệu dự báo · {count}/{required}",
    "Mức thay đổi sử dụng quá nhỏ để ước tính hết hạn",
    "Với tốc độ hiện tại, sẽ hết trong khoảng {duration}",
    "Có khả năng hết trước khi đặt lại · trong khoảng {duration}",
    "Dự kiến còn khoảng {percent}% khi đặt lại",
    "Dự kiến hết sau ít nhất 7 ngày",
    "Đã hết giới hạn",
    "Ẩn dự báo vì dữ liệu đã cũ",
    "Dữ liệu dự báo không khả dụng",
    "phút",
    "phút",
    "giờ",
    "giờ",
    "ngày",
    "ngày",
    "Tốc độ sử dụng: Dư dả",
    "Tốc độ sử dụng: Bình thường",
    "Tốc độ sử dụng: Nhanh",
    "Đang đo tốc độ sử dụng · dữ liệu {count}/{required} · quan sát {minutes}/{required_minutes} phút",
    "Không thể xác định tốc độ sử dụng · cần mức dùng gần đây và thời điểm đặt lại",
    "Hiển thị tốc độ sử dụng đang tắt",
    "Đã dùng {rise}% trong {duration} gần đây · khoảng {rate}% mỗi giờ",
    "Với tốc độ này, khoảng {percent}% sẽ còn lại khi đặt lại",
    "Với tốc độ này, giới hạn có thể hết trước khi đặt lại",
    "CodexPeek {version} đã có sẵn.\n\nCập nhật ngay? Cài đặt của bạn sẽ được giữ nguyên.",
    "Cập nhật ngay",
    "Bỏ qua phiên bản này",
    "Đang tải bản cập nhật",
    "Đang cài đặt bản cập nhật và khởi động lại",
    "Không thể tải bản cập nhật. Hãy kiểm tra cài đặt mạng hoặc proxy rồi thử lại.",
    "Không thể xác minh bản cập nhật đã tải xuống nên bản cập nhật chưa được cài đặt. Hãy cập nhật thủ công từ trang phát hành GitHub.",
    "Không thể cài đặt bản cập nhật. Hãy đóng CodexPeek rồi thử lại, hoặc cập nhật thủ công từ trang phát hành GitHub.",
    "Tệp thực thi CodexPeek này không phải là bản dựng phát hành GitHub chính thức.\n\nCập nhật tự động đã bị tắt. Việc thay thế bằng bản phát hành chính thức sẽ không bao gồm các thay đổi được dựng cục bộ. Để cập nhật, hãy kéo và dựng lại mã nguồn hoặc cài đặt thủ công bản phát hành chính thức.",
];

const TURKISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Sorgulanıyor",
    "Yenileniyor",
    "Kullanım verileri eski",
    "Kullanım kullanılamıyor",
    "Yenile",
    "Şimdi yenile",
    "Yenileme aralığı",
    "Windows ile başlat",
    "Başlangıç görünümü",
    "Widget'ı göster",
    "Yalnızca tepsi",
    "Otomatik kimlik doğrulama yenileme",
    "Codex'te oturum aç",
    "Kimlik doğrulamayı yenile",
    "Dil",
    "Otomatik",
    "Tanılama",
    "Güncellemeleri denetle",
    "Ayarlar",
    "Çıkış",
    "Widget'ı göster",
    "Widget'ı gizle",
    "Başlangıç: widget'ı göster",
    "Başlangıç: yalnızca tepsi",
    "Widget: tüm monitörler",
    "Widget: yalnızca ana monitör",
    "Widget konumu",
    "Tüm monitörler",
    "Yalnızca ana monitör",
    "Bir güncelleme mevcut",
    "Güncelsiniz",
    "Güncellemeler denetleniyor",
    "Güncelleme denetimi başarısız",
    "Codex Kullanım Monitörü",
    "Codex Kullanım Monitörü Ayarları",
    "Codex Kullanım Monitörü Tanılaması",
    "Birincil pencere",
    "İkincil pencere",
    "Codex CLI doğrulanamadı",
    "Codex hizmet isteği başarısız",
    "Oturum açma durumu doğrulanamadı",
    "Ayarlar okunamadı veya doğrulanamadı",
    "Proxy varlığı denetlendi",
    "Görev çubuğu durumu doğrulanamadı",
    "Kalan kullanımı göster",
    "Haftalık kullanımı göster",
    "{version} sürümü kullanılabilir.\n\nGitHub sürüm sayfası açılsın mı?",
    "Güncelleme denetimi başarısız oldu. Ağ veya proxy ayarlarını denetleyip yeniden deneyin.",
    "GitHub sürüm sayfası açılamadı. Varsayılan tarayıcı ayarlarını denetleyin.",
    "Kullanım profilleri",
    "Kullanım profili ekle",
    "Kullanım profillerini yönet",
    "Varsayılan Codex hesabı",
    "Gösteriliyor",
    "Codex CLI oturumu değişmez",
    "Oturum açılması gerekiyor",
    "Kullanım profili ekle",
    "Tarayıcıda kullanılacak hesabı doğrulayın",
    "Yeniden adlandır",
    "Oturum aç",
    "Oturumu kapat",
    "Sil",
    "Bu kullanım profili silinsin mi?",
    "Kullanım profili sınırına ulaşıldı",
    "Kapat",
    "Profil adı",
    "Profil adını kontrol edin",
    "Codex CLI ve IDE oturumları değişmez",
    "Yerel profil verileri kurtarılamaz",
    "Profil işlemi tamamlanamadı",
    "İptal",
    "Sıfırlama kuponları",
    "kullanıldı",
    "biter",
    "Kullanım tahmini",
    "Kullanım tahmini",
    "Kullanım tahmin geçmişini temizle",
    "Kullanım tahmin geçmişi temizlensin mi?",
    "Tahmin verileri toplanıyor · {count}/{required}",
    "Kullanım değişimi tükenmeyi tahmin etmek için çok küçük",
    "Mevcut hızla yaklaşık {duration} içinde tükenir",
    "Sıfırlanmadan önce tükenme olasılığı yüksek · yaklaşık {duration} içinde",
    "Sıfırlamada yaklaşık {percent}% kalması bekleniyor",
    "Tükenmenin en az 7 gün sonra olması bekleniyor",
    "Limit tükendi",
    "Veriler eski olduğu için tahmin gizlendi",
    "Tahmin verileri kullanılamıyor",
    "dakika",
    "dakika",
    "saat",
    "saat",
    "gün",
    "gün",
    "Kullanım hızı: Rahat",
    "Kullanım hızı: Normal",
    "Kullanım hızı: Hızlı",
    "Kullanım hızı ölçülüyor · veri {count}/{required} · gözlem {minutes}/{required_minutes} dk",
    "Kullanım hızı kullanılamıyor · güncel kullanım ve sıfırlama zamanı gerekli",
    "Kullanım hızı göstergesi kapalı",
    "Son {duration} içinde %{rise} kullanıldı · saatte yaklaşık %{rate}",
    "Bu hızla sıfırlamada yaklaşık %{percent} kalır",
    "Bu hızla sınır sıfırlamadan önce tükenebilir",
    "CodexPeek {version} kullanıma hazır.\n\nŞimdi güncellensin mi? Ayarlarınız korunacaktır.",
    "Şimdi güncelle",
    "Bu sürümü atla",
    "Güncelleme indiriliyor",
    "Güncelleme yükleniyor ve yeniden başlatılıyor",
    "Güncelleme indirilemedi. Ağ veya proxy ayarlarınızı kontrol edip yeniden deneyin.",
    "İndirilen güncelleme doğrulanamadığı için yüklenmedi. GitHub sürüm sayfasından elle güncelleyin.",
    "Güncelleme yüklenemedi. CodexPeek’i kapatıp yeniden deneyin veya GitHub sürüm sayfasından elle güncelleyin.",
    "Bu CodexPeek yürütülebilir dosyası resmi bir GitHub sürüm derlemesi değildir.\n\nOtomatik güncellemeler devre dışıdır. Resmi sürümle değiştirilirse yerel olarak derlenen değişiklikler korunmaz. Güncellemek için kaynak kodu çekip yeniden derleyin veya resmi sürümü elle yükleyin.",
];

const ARABIC_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "جارٍ الاستعلام",
    "جارٍ التحديث",
    "بيانات الاستخدام قديمة",
    "الاستخدام غير متاح",
    "تحديث",
    "تحديث الآن",
    "فاصل التحديث",
    "البدء مع Windows",
    "عرض بدء التشغيل",
    "إظهار الويدجت",
    "علبة النظام فقط",
    "تحديث المصادقة تلقائيًا",
    "تسجيل الدخول إلى Codex",
    "تحديث المصادقة",
    "اللغة",
    "تلقائي",
    "التشخيصات",
    "التحقق من التحديثات",
    "الإعدادات",
    "خروج",
    "إظهار الويدجت",
    "إخفاء الويدجت",
    "بدء التشغيل: إظهار الويدجت",
    "بدء التشغيل: علبة النظام فقط",
    "الويدجت: كل الشاشات",
    "الويدجت: الشاشة الرئيسية فقط",
    "موضع الويدجت",
    "كل الشاشات",
    "الشاشة الرئيسية فقط",
    "يتوفر تحديث جديد",
    "أنت تستخدم أحدث إصدار",
    "جارٍ التحقق من التحديثات",
    "فشل التحقق من التحديثات",
    "مراقب استخدام Codex",
    "إعدادات مراقب استخدام Codex",
    "تشخيصات مراقب استخدام Codex",
    "النافذة الرئيسية",
    "النافذة الثانوية",
    "تعذر التحقق من Codex CLI",
    "فشل طلب خدمة Codex",
    "تعذر التحقق من حالة تسجيل الدخول",
    "تعذرت قراءة الإعدادات أو التحقق منها",
    "تم التحقق من وجود الوكيل",
    "تعذر التحقق من حالة شريط المهام",
    "إظهار الاستخدام المتبقي",
    "إظهار الاستخدام الأسبوعي",
    "الإصدار {version} متاح.\n\nهل تريد فتح صفحة الإصدار على GitHub؟",
    "فشل التحقق من التحديث. تحقق من إعدادات الشبكة أو الوكيل ثم أعد المحاولة.",
    "تعذر فتح صفحة الإصدار على GitHub. تحقق من إعدادات المتصفح الافتراضي.",
    "ملفات تعريف الاستخدام",
    "إضافة ملف تعريف استخدام",
    "إدارة ملفات تعريف الاستخدام",
    "حساب Codex الافتراضي",
    "معروض",
    "لا يتغير تسجيل الدخول إلى Codex CLI",
    "تسجيل الدخول مطلوب",
    "إضافة ملف تعريف استخدام",
    "أكد الحساب المراد استخدامه في المتصفح",
    "إعادة التسمية",
    "تسجيل الدخول",
    "تسجيل الخروج",
    "حذف",
    "هل تريد حذف ملف تعريف الاستخدام هذا؟",
    "تم بلوغ حد ملفات تعريف الاستخدام",
    "إغلاق",
    "اسم ملف التعريف",
    "تحقق من اسم ملف التعريف",
    "لا تتغير عمليات تسجيل الدخول في Codex CLI وIDE",
    "لا يمكن استعادة بيانات ملف التعريف المحلية",
    "تعذر إكمال عملية ملف التعريف",
    "إلغاء",
    "قسائم إعادة التعيين",
    "مستخدم",
    "ينتهي",
    "توقع الاستخدام",
    "توقع الاستخدام",
    "مسح سجل توقع الاستخدام",
    "هل تريد مسح سجل توقع الاستخدام؟",
    "جارٍ جمع بيانات التوقع · {count}/{required}",
    "تغير الاستخدام صغير جدًا لتعذر تقدير النفاد",
    "بالمعدل الحالي، ينفد الحد خلال نحو {duration}",
    "يُرجح نفاد الحد قبل إعادة التعيين · خلال نحو {duration}",
    "من المتوقع بقاء نحو {percent}% عند إعادة التعيين",
    "من المتوقع النفاد بعد 7 أيام على الأقل",
    "تم استنفاد الحد",
    "تم إخفاء التوقع لأن البيانات قديمة",
    "بيانات التوقع غير متاحة",
    "دقيقة",
    "دقائق",
    "ساعة",
    "ساعات",
    "يوم",
    "أيام",
    "وتيرة الاستخدام: مريحة",
    "وتيرة الاستخدام: معتدلة",
    "وتيرة الاستخدام: سريعة",
    "جارٍ قياس وتيرة الاستخدام · البيانات {count}/{required} · الرصد {minutes}/{required_minutes} دقيقة",
    "وتيرة الاستخدام غير متاحة · يلزم استخدام حديث ووقت لإعادة التعيين",
    "عرض وتيرة الاستخدام متوقف",
    "تم استخدام {rise}% خلال آخر {duration} · نحو {rate}% في الساعة",
    "بهذه الوتيرة، سيتبقى نحو {percent}% عند إعادة التعيين",
    "بهذه الوتيرة، قد ينفد الحد قبل إعادة التعيين",
    "يتوفر CodexPeek {version}.\n\nهل تريد التحديث الآن؟ سيتم الاحتفاظ بإعداداتك.",
    "التحديث الآن",
    "تخطي هذا الإصدار",
    "جارٍ تنزيل التحديث",
    "جارٍ تثبيت التحديث وإعادة التشغيل",
    "تعذر تنزيل التحديث. تحقق من إعدادات الشبكة أو الوكيل ثم حاول مرة أخرى.",
    "تعذر التحقق من التحديث الذي تم تنزيله، لذلك لم يتم تثبيته. حدّث يدويًا من صفحة الإصدارات على GitHub.",
    "تعذر تثبيت التحديث. أغلق CodexPeek وحاول مرة أخرى، أو حدّث يدويًا من صفحة الإصدارات على GitHub.",
    "ملف CodexPeek التنفيذي هذا ليس إصدارًا رسميًا منشورًا على GitHub.\n\nالتحديثات التلقائية معطلة. استبداله بإصدار رسمي لن يتضمن التغييرات المبنية محليًا. للتحديث، اسحب المصدر وأعد بناءه أو ثبّت إصدارًا رسميًا يدويًا.",
];

/// 지정한 언어와 키에 해당하는 정적 사용자 문구를 반환합니다.
///
/// 매개변수 `key`는 표시할 문구 식별자이고 `language`는 반환 언어입니다.
/// 반환값은 프로그램 전체에서 재사용 가능한 정적 문자열입니다.
pub fn localized_text(key: LocalizationKey, language: Language) -> &'static str {
    let index = key.index();
    match language {
        Language::Korean => KOREAN_TEXT[index],
        Language::English => ENGLISH_TEXT[index],
        Language::Spanish => SPANISH_TEXT[index],
        Language::PortugueseBrazil => PORTUGUESE_BRAZIL_TEXT[index],
        Language::Indonesian => INDONESIAN_TEXT[index],
        Language::Japanese => JAPANESE_TEXT[index],
        Language::Hindi => HINDI_TEXT[index],
        Language::German => GERMAN_TEXT[index],
        Language::French => FRENCH_TEXT[index],
        Language::Vietnamese => VIETNAMESE_TEXT[index],
        Language::Turkish => TURKISH_TEXT[index],
        Language::Arabic => ARABIC_TEXT[index],
    }
}

/// 갱신 간격 값을 하위 메뉴의 짧은 선택 문구로 만듭니다.
///
/// `minutes`는 지원되는 자동 갱신 간격이며, 호출자가 메뉴 동작 검증을 별도로 수행합니다.
pub(crate) fn localized_refresh_interval_choice_text(minutes: u32, language: Language) -> String {
    match language {
        Language::Korean => format!("{minutes}분"),
        Language::English | Language::Spanish | Language::PortugueseBrazil | Language::French => {
            format!("{minutes} min")
        }
        Language::Indonesian => format!("{minutes} mnt"),
        Language::Japanese => format!("{minutes}分"),
        Language::Hindi => format!("{minutes} मिनट"),
        Language::German => format!("{minutes} Min."),
        Language::Vietnamese => format!("{minutes} phút"),
        Language::Turkish => format!("{minutes} dk"),
        Language::Arabic => format!("{minutes} دقيقة"),
    }
}

#[cfg(test)]
mod tests {
    use super::{
        localized_refresh_interval_choice_text, localized_text, Language, LocalizationKey,
    };

    #[test]
    fn every_key_has_a_nonempty_translation() {
        for key in LocalizationKey::ALL {
            for language in Language::ALL {
                assert!(!localized_text(*key, *language).trim().is_empty());
            }
        }
    }

    #[test]
    fn refresh_interval_choice_text_includes_value_and_unit() {
        assert_eq!(
            localized_refresh_interval_choice_text(15, Language::Korean),
            "15분"
        );
        assert_eq!(
            localized_refresh_interval_choice_text(15, Language::English),
            "15 min"
        );
        for language in Language::ALL {
            let text = localized_refresh_interval_choice_text(15, *language);
            assert!(text.contains("15"), "{language:?}: {text}");
        }
    }
}
