/// 사용자에게 표시할 문구의 언어를 나타냅니다.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Language {
    /// 한국어 문구를 사용합니다.
    Korean,
    /// 영어 문구를 사용합니다.
    English,
    /// 스페인어 문구를 사용합니다.
    Spanish,
    /// 브라질 포르투갈어 문구를 사용합니다.
    PortugueseBrazil,
    /// 인도네시아어 문구를 사용합니다.
    Indonesian,
    /// 일본어 문구를 사용합니다.
    Japanese,
    /// 힌디어 문구를 사용합니다.
    Hindi,
    /// 독일어 문구를 사용합니다.
    German,
    /// 프랑스어 문구를 사용합니다.
    French,
    /// 베트남어 문구를 사용합니다.
    Vietnamese,
    /// 터키어 문구를 사용합니다.
    Turkish,
    /// 아랍어 문구를 사용합니다.
    Arabic,
}

impl Language {
    /// UI에서 지원하는 모든 언어를 표시 순서대로 반환합니다.
    pub const ALL: &'static [Self] = &[
        Self::Korean,
        Self::English,
        Self::Spanish,
        Self::PortugueseBrazil,
        Self::Indonesian,
        Self::Japanese,
        Self::Hindi,
        Self::German,
        Self::French,
        Self::Vietnamese,
        Self::Turkish,
        Self::Arabic,
    ];
}

/// 지원하는 모든 정적 지역화 문구의 식별자입니다.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LocalizationKey {
    /// 자동 갱신 상태입니다.
    Polling,
    /// 수동 갱신 상태입니다.
    Refreshing,
    /// 오래된 사용량 상태입니다.
    Stale,
    /// 사용량을 불러오지 못한 상태입니다.
    Unavailable,
    /// 새로 고침 메뉴입니다.
    MenuRefresh,
    /// 즉시 새로 고침 메뉴입니다.
    MenuRefreshNow,
    /// 갱신 간격 메뉴입니다.
    MenuRefreshInterval,
    /// 자동 시작 메뉴입니다.
    MenuAutostart,
    /// 시작 화면 메뉴입니다.
    MenuStartupView,
    /// 시작 시 위젯 표시 옵션입니다.
    MenuStartupWidget,
    /// 시작 시 트레이 전용 옵션입니다.
    MenuStartupTrayOnly,
    /// 자동 인증 갱신 메뉴입니다.
    MenuAuthRefresh,
    /// Codex 로그인 메뉴입니다.
    MenuLogin,
    /// 인증을 즉시 갱신하는 메뉴입니다.
    MenuAuthRefreshNow,
    /// 언어 메뉴입니다.
    MenuLanguage,
    /// 언어 자동 선택 항목입니다.
    MenuLanguageAutomaticChoice,
    /// 진단 메뉴입니다.
    MenuDiagnostics,
    /// 업데이트 확인 메뉴입니다.
    MenuUpdateCheck,
    /// 설정 메뉴입니다.
    MenuSettings,
    /// 종료 메뉴입니다.
    MenuExit,
    /// 위젯 표시 메뉴입니다.
    MenuShowWidget,
    /// 위젯 숨김 메뉴입니다.
    MenuHideWidget,
    /// 시작 시 위젯 표시 선택 메뉴입니다.
    MenuStartupWidgetChoice,
    /// 시작 시 트레이 전용 선택 메뉴입니다.
    MenuStartupTrayOnlyChoice,
    /// 모든 모니터 작업표시줄 표시 메뉴입니다.
    MenuTaskbarAll,
    /// 주 모니터 작업표시줄 표시 메뉴입니다.
    MenuTaskbarPrimary,
    /// 위젯 표시 위치 메뉴입니다.
    MenuWidgetPlacement,
    /// 모든 모니터 선택 항목입니다.
    MenuTaskbarAllChoice,
    /// 주 모니터 선택 항목입니다.
    MenuTaskbarPrimaryChoice,
    /// 업데이트 가능 알림입니다.
    UpdateAvailable,
    /// 최신 상태 알림입니다.
    UpdateCurrent,
    /// 업데이트 확인 진행 상태 알림입니다.
    UpdateChecking,
    /// 업데이트 확인 실패 상태 알림입니다.
    UpdateFailed,
    /// 기본 창 제목입니다.
    WindowTitle,
    /// 설정 창 제목입니다.
    SettingsTitle,
    /// 진단 창 제목입니다.
    DiagnosticsTitle,
    /// 주 사용량 창 레이블입니다.
    PrimaryWindowLabel,
    /// 보조 사용량 창 레이블입니다.
    SecondaryWindowLabel,
    /// CLI 진단 문구입니다.
    DiagnosticCli,
    /// RPC 진단 문구입니다.
    DiagnosticRpc,
    /// 로그인 진단 문구입니다.
    DiagnosticLogin,
    /// 설정 진단 문구입니다.
    DiagnosticSettings,
    /// 프록시 진단 문구입니다.
    DiagnosticProxy,
    /// 작업 표시줄 진단 문구입니다.
    DiagnosticTaskbar,
    /// 남은 사용량 표시 전환 메뉴입니다.
    MenuShowRemaining,
    /// 주간 사용량 표시 전환 메뉴입니다.
    MenuShowWeekly,
    /// 새 버전과 GitHub 릴리스 페이지 열기를 확인하는 문구입니다.
    UpdateAvailablePrompt,
    /// 업데이트 확인 실패 후 복구 방법을 안내하는 문구입니다.
    UpdateFailedHelp,
    /// GitHub 릴리스 페이지 열기 실패 안내입니다.
    UpdateOpenFailed,
    /// 사용량 프로필 선택 메뉴입니다.
    MenuUsageProfiles,
    /// 사용량 프로필 추가 메뉴입니다.
    MenuAddUsageProfile,
    /// 사용량 프로필 관리 메뉴입니다.
    MenuManageUsageProfiles,
    /// 시스템 Codex 프로필 이름입니다.
    UsageProfileSystem,
    /// 현재 표시 중인 프로필 상태입니다.
    UsageProfileDisplayed,
    /// Codex CLI 로그인이 바뀌지 않는다는 안내입니다.
    UsageProfileCliUnchanged,
    /// 프로필 로그인이 필요하다는 상태입니다.
    UsageProfileLoginRequired,
    /// 사용량 프로필 추가 창 제목입니다.
    UsageProfileAddTitle,
    /// 브라우저에서 계정을 확인하라는 안내입니다.
    UsageProfileConfirmBrowserAccount,
    /// 프로필 이름 변경 동작입니다.
    UsageProfileRename,
    /// 프로필 로그인 동작입니다.
    UsageProfileLogin,
    /// 프로필 로그아웃 동작입니다.
    UsageProfileLogout,
    /// 프로필 삭제 동작입니다.
    UsageProfileDelete,
    /// 프로필 삭제 확인 문구입니다.
    UsageProfileDeleteConfirm,
    /// 프로필 개수 제한 안내입니다.
    UsageProfileLimitReached,
    /// 프로필 관리 대화상자의 닫기 동작입니다.
    UsageProfileClose,
    /// 프로필 표시 이름 입력 레이블입니다.
    UsageProfileName,
    /// 프로필 표시 이름 검증 실패 안내입니다.
    UsageProfileInvalidLabel,
    /// 프로필 로그인과 기존 CLI·IDE 로그인의 격리 안내입니다.
    UsageProfileCliIdeUnchanged,
    /// 로컬 프로필 데이터 삭제의 복구 불가 안내입니다.
    UsageProfileDeleteIrrecoverable,
    /// 프로필 대화상자 작업 실패의 안전한 안내입니다.
    UsageProfileOperationFailed,
    /// 프로필 추가 입력창을 닫는 동작입니다.
    UsageProfileCancel,
    /// 프로필별 사용 가능한 리셋권 수를 나타내는 레이블입니다.
    UsageProfileResetCredits,
    /// 프로필별 한도 소모율을 나타내는 레이블입니다.
    UsageProfileUsed,
    /// 프로필별 리셋권 또는 한도의 종료 시각을 나타내는 레이블입니다.
    UsageProfileEnds,
    /// 사용량 소진 예측 하위 메뉴입니다.
    MenuUsageForecast,
    /// 사용량 소진 예측 기록과 표시를 전환하는 메뉴입니다.
    MenuUsageForecastToggle,
    /// 사용량 소진 예측 기록을 삭제하는 메뉴입니다.
    MenuUsageForecastClearHistory,
    /// 사용량 소진 예측 기록 삭제 확인 문구입니다.
    UsageForecastClearConfirm,
}

impl LocalizationKey {
    /// 모든 문구 키를 빠짐없이 반환합니다.
    pub const ALL: &'static [Self] = &[
        Self::Polling,
        Self::Refreshing,
        Self::Stale,
        Self::Unavailable,
        Self::MenuRefresh,
        Self::MenuRefreshNow,
        Self::MenuRefreshInterval,
        Self::MenuAutostart,
        Self::MenuStartupView,
        Self::MenuStartupWidget,
        Self::MenuStartupTrayOnly,
        Self::MenuAuthRefresh,
        Self::MenuLogin,
        Self::MenuAuthRefreshNow,
        Self::MenuLanguage,
        Self::MenuLanguageAutomaticChoice,
        Self::MenuDiagnostics,
        Self::MenuUpdateCheck,
        Self::MenuSettings,
        Self::MenuExit,
        Self::MenuShowWidget,
        Self::MenuHideWidget,
        Self::MenuStartupWidgetChoice,
        Self::MenuStartupTrayOnlyChoice,
        Self::MenuTaskbarAll,
        Self::MenuTaskbarPrimary,
        Self::MenuWidgetPlacement,
        Self::MenuTaskbarAllChoice,
        Self::MenuTaskbarPrimaryChoice,
        Self::UpdateAvailable,
        Self::UpdateCurrent,
        Self::UpdateChecking,
        Self::UpdateFailed,
        Self::WindowTitle,
        Self::SettingsTitle,
        Self::DiagnosticsTitle,
        Self::PrimaryWindowLabel,
        Self::SecondaryWindowLabel,
        Self::DiagnosticCli,
        Self::DiagnosticRpc,
        Self::DiagnosticLogin,
        Self::DiagnosticSettings,
        Self::DiagnosticProxy,
        Self::DiagnosticTaskbar,
        Self::MenuShowRemaining,
        Self::MenuShowWeekly,
        Self::UpdateAvailablePrompt,
        Self::UpdateFailedHelp,
        Self::UpdateOpenFailed,
        Self::MenuUsageProfiles,
        Self::MenuAddUsageProfile,
        Self::MenuManageUsageProfiles,
        Self::UsageProfileSystem,
        Self::UsageProfileDisplayed,
        Self::UsageProfileCliUnchanged,
        Self::UsageProfileLoginRequired,
        Self::UsageProfileAddTitle,
        Self::UsageProfileConfirmBrowserAccount,
        Self::UsageProfileRename,
        Self::UsageProfileLogin,
        Self::UsageProfileLogout,
        Self::UsageProfileDelete,
        Self::UsageProfileDeleteConfirm,
        Self::UsageProfileLimitReached,
        Self::UsageProfileClose,
        Self::UsageProfileName,
        Self::UsageProfileInvalidLabel,
        Self::UsageProfileCliIdeUnchanged,
        Self::UsageProfileDeleteIrrecoverable,
        Self::UsageProfileOperationFailed,
        Self::UsageProfileCancel,
        Self::UsageProfileResetCredits,
        Self::UsageProfileUsed,
        Self::UsageProfileEnds,
        Self::MenuUsageForecast,
        Self::MenuUsageForecastToggle,
        Self::MenuUsageForecastClearHistory,
        Self::UsageForecastClearConfirm,
    ];

    const fn index(self) -> usize {
        match self {
            Self::Polling => 0,
            Self::Refreshing => 1,
            Self::Stale => 2,
            Self::Unavailable => 3,
            Self::MenuRefresh => 4,
            Self::MenuRefreshNow => 5,
            Self::MenuRefreshInterval => 6,
            Self::MenuAutostart => 7,
            Self::MenuStartupView => 8,
            Self::MenuStartupWidget => 9,
            Self::MenuStartupTrayOnly => 10,
            Self::MenuAuthRefresh => 11,
            Self::MenuLogin => 12,
            Self::MenuAuthRefreshNow => 13,
            Self::MenuLanguage => 14,
            Self::MenuLanguageAutomaticChoice => 15,
            Self::MenuDiagnostics => 16,
            Self::MenuUpdateCheck => 17,
            Self::MenuSettings => 18,
            Self::MenuExit => 19,
            Self::MenuShowWidget => 20,
            Self::MenuHideWidget => 21,
            Self::MenuStartupWidgetChoice => 22,
            Self::MenuStartupTrayOnlyChoice => 23,
            Self::MenuTaskbarAll => 24,
            Self::MenuTaskbarPrimary => 25,
            Self::MenuWidgetPlacement => 26,
            Self::MenuTaskbarAllChoice => 27,
            Self::MenuTaskbarPrimaryChoice => 28,
            Self::UpdateAvailable => 29,
            Self::UpdateCurrent => 30,
            Self::UpdateChecking => 31,
            Self::UpdateFailed => 32,
            Self::WindowTitle => 33,
            Self::SettingsTitle => 34,
            Self::DiagnosticsTitle => 35,
            Self::PrimaryWindowLabel => 36,
            Self::SecondaryWindowLabel => 37,
            Self::DiagnosticCli => 38,
            Self::DiagnosticRpc => 39,
            Self::DiagnosticLogin => 40,
            Self::DiagnosticSettings => 41,
            Self::DiagnosticProxy => 42,
            Self::DiagnosticTaskbar => 43,
            Self::MenuShowRemaining => 44,
            Self::MenuShowWeekly => 45,
            Self::UpdateAvailablePrompt => 46,
            Self::UpdateFailedHelp => 47,
            Self::UpdateOpenFailed => 48,
            Self::MenuUsageProfiles => 49,
            Self::MenuAddUsageProfile => 50,
            Self::MenuManageUsageProfiles => 51,
            Self::UsageProfileSystem => 52,
            Self::UsageProfileDisplayed => 53,
            Self::UsageProfileCliUnchanged => 54,
            Self::UsageProfileLoginRequired => 55,
            Self::UsageProfileAddTitle => 56,
            Self::UsageProfileConfirmBrowserAccount => 57,
            Self::UsageProfileRename => 58,
            Self::UsageProfileLogin => 59,
            Self::UsageProfileLogout => 60,
            Self::UsageProfileDelete => 61,
            Self::UsageProfileDeleteConfirm => 62,
            Self::UsageProfileLimitReached => 63,
            Self::UsageProfileClose => 64,
            Self::UsageProfileName => 65,
            Self::UsageProfileInvalidLabel => 66,
            Self::UsageProfileCliIdeUnchanged => 67,
            Self::UsageProfileDeleteIrrecoverable => 68,
            Self::UsageProfileOperationFailed => 69,
            Self::UsageProfileCancel => 70,
            Self::UsageProfileResetCredits => 71,
            Self::UsageProfileUsed => 72,
            Self::UsageProfileEnds => 73,
            Self::MenuUsageForecast => 74,
            Self::MenuUsageForecastToggle => 75,
            Self::MenuUsageForecastClearHistory => 76,
            Self::UsageForecastClearConfirm => 77,
        }
    }
}

const LOCALIZATION_KEY_COUNT: usize = 78;

const KOREAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "자동 갱신 중",
    "새로 고치는 중",
    "정보가 오래되었습니다",
    "사용량 정보를 사용할 수 없습니다",
    "새로 고침",
    "지금 갱신",
    "갱신 간격",
    "Windows 시작 시 실행",
    "시작 화면",
    "위젯 표시",
    "트레이에만 표시",
    "자동 인증 갱신",
    "Codex 로그인",
    "인증 갱신",
    "언어",
    "자동",
    "진단",
    "업데이트 확인",
    "설정",
    "종료",
    "위젯 표시",
    "위젯 숨기기",
    "시작: 위젯 표시",
    "시작: 트레이만",
    "위젯: 모든 모니터",
    "위젯: 주 모니터만",
    "위젯 위치",
    "모든 모니터",
    "주 모니터만",
    "새 업데이트를 사용할 수 있습니다",
    "최신 버전입니다",
    "업데이트를 확인하는 중입니다",
    "업데이트 확인에 실패했습니다",
    "Codex 사용량 모니터",
    "Codex 사용량 모니터 설정",
    "Codex 사용량 모니터 진단",
    "주 사용량 창",
    "보조 사용량 창",
    "Codex CLI를 확인할 수 없습니다",
    "Codex 서비스 요청에 실패했습니다",
    "로그인 상태를 확인할 수 없습니다",
    "설정을 읽거나 검증할 수 없습니다",
    "프록시 사용 여부를 확인했습니다",
    "작업 표시줄 상태를 확인할 수 없습니다",
    "남은 사용량 표시",
    "주간 사용량 표시",
    "버전 {version}을 사용할 수 있습니다.\n\nGitHub 릴리스 페이지를 여시겠습니까?",
    "업데이트 확인에 실패했습니다. 네트워크 또는 프록시 설정을 확인한 후 다시 시도하세요.",
    "GitHub 릴리스 페이지를 열 수 없습니다. 기본 브라우저 설정을 확인하세요.",
    "사용량 프로필",
    "사용량 프로필 추가",
    "사용량 프로필 관리",
    "기본 Codex 계정",
    "표시 중",
    "Codex CLI 로그인은 변경되지 않습니다",
    "로그인 필요",
    "사용량 프로필 추가",
    "브라우저에서 사용할 계정을 확인하세요",
    "이름 변경",
    "로그인",
    "로그아웃",
    "삭제",
    "이 사용량 프로필을 삭제할까요?",
    "최대 사용량 프로필 수에 도달했습니다",
    "닫기",
    "프로필 이름",
    "프로필 이름을 확인하세요",
    "Codex CLI와 IDE 로그인은 변경되지 않습니다",
    "로컬 프로필 데이터는 복구할 수 없습니다",
    "프로필 작업을 완료할 수 없습니다",
    "취소",
    "리셋 쿠폰",
    "소모",
    "종료",
    "사용량 소진 예측",
    "사용량 소진 예측",
    "사용량 예측 기록 삭제",
    "사용량 소진 예측 기록을 삭제할까요?",
];

const ENGLISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Polling",
    "Refreshing",
    "Usage data is stale",
    "Usage unavailable",
    "Refresh",
    "Refresh now",
    "Refresh interval",
    "Start with Windows",
    "Startup view",
    "Show widget",
    "Tray only",
    "Automatic authentication refresh",
    "Sign in to Codex",
    "Refresh authentication",
    "Language",
    "Automatic",
    "Diagnostics",
    "Check for updates",
    "Settings",
    "Exit",
    "Show widget",
    "Hide widget",
    "Startup: show widget",
    "Startup: tray only",
    "Widget: all monitors",
    "Widget: primary monitor only",
    "Widget placement",
    "All monitors",
    "Primary monitor only",
    "An update is available",
    "You are up to date",
    "Checking for updates",
    "Update check failed",
    "Codex Usage Monitor",
    "Codex Usage Monitor Settings",
    "Codex Usage Monitor Diagnostics",
    "Primary window",
    "Secondary window",
    "Codex CLI could not be verified",
    "Codex service request failed",
    "Login status could not be verified",
    "Settings could not be read or validated",
    "Proxy presence was checked",
    "Taskbar status could not be verified",
    "Show remaining usage",
    "Show weekly usage",
    "Version {version} is available.\n\nOpen the GitHub release page?",
    "The update check failed. Check your network or proxy settings and try again.",
    "The GitHub release page could not be opened. Check your default browser settings.",
    "Usage profiles",
    "Add usage profile",
    "Manage usage profiles",
    "Default Codex account",
    "Displayed",
    "Codex CLI sign-in is unchanged",
    "Sign-in required",
    "Add usage profile",
    "Confirm the account to use in your browser",
    "Rename",
    "Sign in",
    "Sign out",
    "Delete",
    "Delete this usage profile?",
    "The usage profile limit has been reached",
    "Close",
    "Profile name",
    "Check the profile name",
    "Codex CLI and IDE sign-ins are unchanged",
    "local profile data cannot be recovered",
    "The profile operation could not be completed",
    "Cancel",
    "Reset coupons",
    "used",
    "ends",
    "Usage forecasting",
    "Usage forecasting",
    "Clear usage forecast history",
    "Clear the usage forecast history?",
];

const SPANISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Consultando",
    "Actualizando",
    "Los datos de uso no están actualizados",
    "Uso no disponible",
    "Actualizar",
    "Actualizar ahora",
    "Intervalo de actualización",
    "Iniciar con Windows",
    "Vista inicial",
    "Mostrar widget",
    "Solo bandeja",
    "Actualización automática de autenticación",
    "Iniciar sesión en Codex",
    "Actualizar autenticación",
    "Idioma",
    "Automático",
    "Diagnóstico",
    "Buscar actualizaciones",
    "Configuración",
    "Salir",
    "Mostrar widget",
    "Ocultar widget",
    "Inicio: mostrar widget",
    "Inicio: solo bandeja",
    "Widget: todos los monitores",
    "Widget: solo monitor principal",
    "Ubicación del widget",
    "Todos los monitores",
    "Solo monitor principal",
    "Hay una actualización disponible",
    "Tienes la versión más reciente",
    "Buscando actualizaciones",
    "Error al buscar actualizaciones",
    "Monitor de uso de Codex",
    "Configuración del monitor de uso de Codex",
    "Diagnóstico del monitor de uso de Codex",
    "Ventana principal",
    "Ventana secundaria",
    "No se pudo verificar Codex CLI",
    "Falló la solicitud del servicio Codex",
    "No se pudo verificar el inicio de sesión",
    "No se pudo leer o validar la configuración",
    "Se comprobó la presencia de proxy",
    "No se pudo verificar el estado de la barra de tareas",
    "Mostrar uso restante",
    "Mostrar uso semanal",
    "La versión {version} está disponible.\n\n¿Abrir la página de la versión en GitHub?",
    "La búsqueda de actualizaciones falló. Comprueba la configuración de red o proxy e inténtalo de nuevo.",
    "No se pudo abrir la página de la versión en GitHub. Comprueba la configuración del navegador predeterminado.",
    "Perfiles de uso",
    "Añadir perfil de uso",
    "Administrar perfiles de uso",
    "Cuenta predeterminada de Codex",
    "Mostrado",
    "El inicio de sesión de Codex CLI no cambia",
    "Inicio de sesión necesario",
    "Añadir perfil de uso",
    "Confirma en el navegador la cuenta que quieres usar",
    "Cambiar nombre",
    "Iniciar sesión",
    "Cerrar sesión",
    "Eliminar",
    "¿Eliminar este perfil de uso?",
    "Se alcanzó el límite de perfiles de uso",
    "Cerrar",
    "Nombre del perfil",
    "Comprueba el nombre del perfil",
    "Los inicios de sesión de Codex CLI e IDE no cambian",
    "Los datos locales del perfil no se pueden recuperar",
    "No se pudo completar la operación del perfil",
    "Cancelar",
    "Cupones de reinicio",
    "usado",
    "termina",
    "Predicción de uso",
    "Predicción de uso",
    "Borrar el historial de predicción de uso",
    "¿Borrar el historial de predicción de uso?",
];

const PORTUGUESE_BRAZIL_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Consultando",
    "Atualizando",
    "Os dados de uso estão desatualizados",
    "Uso indisponível",
    "Atualizar",
    "Atualizar agora",
    "Intervalo de atualização",
    "Iniciar com Windows",
    "Tela inicial",
    "Mostrar widget",
    "Somente bandeja",
    "Atualização automática da autenticação",
    "Entrar no Codex",
    "Atualizar autenticação",
    "Idioma",
    "Automático",
    "Diagnóstico",
    "Verificar atualizações",
    "Configurações",
    "Sair",
    "Mostrar widget",
    "Ocultar widget",
    "Inicialização: mostrar widget",
    "Inicialização: somente bandeja",
    "Widget: todos os monitores",
    "Widget: somente monitor principal",
    "Posição do widget",
    "Todos os monitores",
    "Somente monitor principal",
    "Há uma atualização disponível",
    "Você está na versão mais recente",
    "Verificando atualizações",
    "Falha ao verificar atualizações",
    "Monitor de uso do Codex",
    "Configurações do monitor de uso do Codex",
    "Diagnóstico do monitor de uso do Codex",
    "Janela principal",
    "Janela secundária",
    "Não foi possível verificar o Codex CLI",
    "Falha na solicitação do serviço Codex",
    "Não foi possível verificar o login",
    "Não foi possível ler ou validar as configurações",
    "A presença de proxy foi verificada",
    "Não foi possível verificar o status da barra de tarefas",
    "Mostrar uso restante",
    "Mostrar uso semanal",
    "A versão {version} está disponível.\n\nAbrir a página da versão no GitHub?",
    "A verificação de atualizações falhou. Verifique as configurações de rede ou proxy e tente novamente.",
    "Não foi possível abrir a página da versão no GitHub. Verifique as configurações do navegador padrão.",
    "Perfis de uso",
    "Adicionar perfil de uso",
    "Gerenciar perfis de uso",
    "Conta padrão do Codex",
    "Exibido",
    "O login do Codex CLI não é alterado",
    "Login necessário",
    "Adicionar perfil de uso",
    "Confirme no navegador a conta que deseja usar",
    "Renomear",
    "Entrar",
    "Sair",
    "Excluir",
    "Excluir este perfil de uso?",
    "O limite de perfis de uso foi atingido",
    "Fechar",
    "Nome do perfil",
    "Verifique o nome do perfil",
    "Os logins do Codex CLI e da IDE não são alterados",
    "Os dados locais do perfil não podem ser recuperados",
    "Não foi possível concluir a operação do perfil",
    "Cancelar",
    "Cupons de redefinição",
    "usado",
    "termina",
    "Previsão de uso",
    "Previsão de uso",
    "Limpar histórico de previsão de uso",
    "Limpar o histórico de previsão de uso?",
];

const INDONESIAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Memeriksa",
    "Menyegarkan",
    "Data penggunaan sudah lama",
    "Penggunaan tidak tersedia",
    "Segarkan",
    "Segarkan sekarang",
    "Interval penyegaran",
    "Mulai bersama Windows",
    "Tampilan awal",
    "Tampilkan widget",
    "Hanya baki sistem",
    "Penyegaran autentikasi otomatis",
    "Masuk ke Codex",
    "Segarkan autentikasi",
    "Bahasa",
    "Otomatis",
    "Diagnostik",
    "Periksa pembaruan",
    "Pengaturan",
    "Keluar",
    "Tampilkan widget",
    "Sembunyikan widget",
    "Awal: tampilkan widget",
    "Awal: hanya baki sistem",
    "Widget: semua monitor",
    "Widget: hanya monitor utama",
    "Posisi widget",
    "Semua monitor",
    "Hanya monitor utama",
    "Pembaruan tersedia",
    "Anda sudah menggunakan versi terbaru",
    "Memeriksa pembaruan",
    "Pemeriksaan pembaruan gagal",
    "Monitor Penggunaan Codex",
    "Pengaturan Monitor Penggunaan Codex",
    "Diagnostik Monitor Penggunaan Codex",
    "Jendela utama",
    "Jendela sekunder",
    "Codex CLI tidak dapat diverifikasi",
    "Permintaan layanan Codex gagal",
    "Status login tidak dapat diverifikasi",
    "Pengaturan tidak dapat dibaca atau divalidasi",
    "Keberadaan proxy telah diperiksa",
    "Status taskbar tidak dapat diverifikasi",
    "Tampilkan sisa penggunaan",
    "Tampilkan penggunaan mingguan",
    "Versi {version} tersedia.\n\nBuka halaman rilis GitHub?",
    "Pemeriksaan pembaruan gagal. Periksa pengaturan jaringan atau proksi, lalu coba lagi.",
    "Halaman rilis GitHub tidak dapat dibuka. Periksa pengaturan browser default.",
    "Profil penggunaan",
    "Tambah profil penggunaan",
    "Kelola profil penggunaan",
    "Akun Codex default",
    "Ditampilkan",
    "Login Codex CLI tidak berubah",
    "Perlu login",
    "Tambah profil penggunaan",
    "Konfirmasikan akun yang akan digunakan di browser",
    "Ganti nama",
    "Masuk",
    "Keluar",
    "Hapus",
    "Hapus profil penggunaan ini?",
    "Batas profil penggunaan telah tercapai",
    "Tutup",
    "Nama profil",
    "Periksa nama profil",
    "Login Codex CLI dan IDE tidak berubah",
    "Data profil lokal tidak dapat dipulihkan",
    "Operasi profil tidak dapat diselesaikan",
    "Batal",
    "Kupon reset",
    "digunakan",
    "berakhir",
    "Prediksi penggunaan",
    "Prediksi penggunaan",
    "Hapus riwayat prediksi penggunaan",
    "Hapus riwayat prediksi penggunaan?",
];

const JAPANESE_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "自動更新中",
    "更新中",
    "使用量データが古くなっています",
    "使用量を利用できません",
    "更新",
    "今すぐ更新",
    "更新間隔",
    "Windows 起動時に実行",
    "起動時の表示",
    "ウィジェットを表示",
    "トレイのみ",
    "認証の自動更新",
    "Codex にログイン",
    "認証を更新",
    "言語",
    "自動",
    "診断",
    "更新を確認",
    "設定",
    "終了",
    "ウィジェットを表示",
    "ウィジェットを隠す",
    "起動: ウィジェットを表示",
    "起動: トレイのみ",
    "ウィジェット: すべてのモニター",
    "ウィジェット: メインモニターのみ",
    "ウィジェットの配置",
    "すべてのモニター",
    "メインモニターのみ",
    "新しい更新があります",
    "最新バージョンです",
    "更新を確認中",
    "更新の確認に失敗しました",
    "Codex 使用量モニター",
    "Codex 使用量モニター設定",
    "Codex 使用量モニター診断",
    "メインウィンドウ",
    "サブウィンドウ",
    "Codex CLI を確認できませんでした",
    "Codex サービス要求に失敗しました",
    "ログイン状態を確認できませんでした",
    "設定を読み取りまたは検証できませんでした",
    "プロキシの有無を確認しました",
    "タスクバーの状態を確認できませんでした",
    "残り使用量を表示",
    "週間使用量を表示",
    "バージョン {version} を利用できます。\n\nGitHub のリリースページを開きますか？",
    "更新の確認に失敗しました。ネットワークまたはプロキシ設定を確認して、もう一度お試しください。",
    "GitHub のリリースページを開けませんでした。既定のブラウザー設定を確認してください。",
    "使用量プロファイル",
    "使用量プロファイルを追加",
    "使用量プロファイルを管理",
    "デフォルトの Codex アカウント",
    "表示中",
    "Codex CLI のサインインは変更されません",
    "サインインが必要です",
    "使用量プロファイルを追加",
    "ブラウザーで使用するアカウントを確認してください",
    "名前を変更",
    "サインイン",
    "サインアウト",
    "削除",
    "この使用量プロファイルを削除しますか？",
    "使用量プロファイルの上限に達しました",
    "閉じる",
    "プロファイル名",
    "プロファイル名を確認してください",
    "Codex CLI と IDE のサインインは変更されません",
    "ローカルプロファイルデータは復元できません",
    "プロファイル操作を完了できませんでした",
    "キャンセル",
    "リセットクーポン",
    "使用済み",
    "終了",
    "使用量の予測",
    "使用量の予測",
    "使用量予測の履歴を消去",
    "使用量予測の履歴を消去しますか？",
];

const HINDI_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "पोलिंग",
    "रीफ़्रेश हो रहा है",
    "उपयोग डेटा पुराना है",
    "उपयोग उपलब्ध नहीं",
    "रीफ़्रेश",
    "अभी रीफ़्रेश करें",
    "रीफ़्रेश अंतराल",
    "Windows के साथ शुरू करें",
    "स्टार्टअप दृश्य",
    "विजेट दिखाएँ",
    "केवल ट्रे",
    "स्वचालित प्रमाणीकरण रीफ़्रेश",
    "Codex में साइन इन करें",
    "प्रमाणीकरण रीफ़्रेश करें",
    "भाषा",
    "स्वतः",
    "निदान",
    "अपडेट जाँचें",
    "सेटिंग्स",
    "बाहर निकलें",
    "विजेट दिखाएँ",
    "विजेट छिपाएँ",
    "स्टार्टअप: विजेट दिखाएँ",
    "स्टार्टअप: केवल ट्रे",
    "विजेट: सभी मॉनिटर",
    "विजेट: केवल मुख्य मॉनिटर",
    "विजेट स्थान",
    "सभी मॉनिटर",
    "केवल मुख्य मॉनिटर",
    "अपडेट उपलब्ध है",
    "आप नवीनतम संस्करण पर हैं",
    "अपडेट जाँचे जा रहे हैं",
    "अपडेट जाँच विफल रही",
    "Codex उपयोग मॉनिटर",
    "Codex उपयोग मॉनिटर सेटिंग्स",
    "Codex उपयोग मॉनिटर निदान",
    "मुख्य विंडो",
    "द्वितीयक विंडो",
    "Codex CLI सत्यापित नहीं हो सका",
    "Codex सेवा अनुरोध विफल रहा",
    "लॉगिन स्थिति सत्यापित नहीं हो सकी",
    "सेटिंग्स पढ़ी या सत्यापित नहीं की जा सकीं",
    "प्रॉक्सी की उपस्थिति जाँची गई",
    "टास्कबार स्थिति सत्यापित नहीं हो सकी",
    "शेष उपयोग दिखाएँ",
    "साप्ताहिक उपयोग दिखाएँ",
    "संस्करण {version} उपलब्ध है।\n\nGitHub रिलीज़ पृष्ठ खोलें?",
    "अपडेट जाँच विफल रही। नेटवर्क या प्रॉक्सी सेटिंग जाँचें और फिर से प्रयास करें।",
    "GitHub रिलीज़ पृष्ठ नहीं खुल सका। डिफ़ॉल्ट ब्राउज़र सेटिंग जाँचें।",
    "उपयोग प्रोफ़ाइल",
    "उपयोग प्रोफ़ाइल जोड़ें",
    "उपयोग प्रोफ़ाइल प्रबंधित करें",
    "डिफ़ॉल्ट Codex खाता",
    "प्रदर्शित",
    "Codex CLI साइन-इन अपरिवर्तित रहता है",
    "साइन-इन आवश्यक",
    "उपयोग प्रोफ़ाइल जोड़ें",
    "ब्राउज़र में उपयोग करने वाला खाता सुनिश्चित करें",
    "नाम बदलें",
    "साइन इन करें",
    "साइन आउट करें",
    "हटाएँ",
    "यह उपयोग प्रोफ़ाइल हटाएँ?",
    "उपयोग प्रोफ़ाइल की सीमा पूरी हो गई है",
    "बंद करें",
    "प्रोफ़ाइल का नाम",
    "प्रोफ़ाइल का नाम जाँचें",
    "Codex CLI और IDE साइन-इन अपरिवर्तित रहते हैं",
    "स्थानीय प्रोफ़ाइल डेटा पुनर्प्राप्त नहीं किया जा सकता",
    "प्रोफ़ाइल कार्रवाई पूरी नहीं हो सकी",
    "रद्द करें",
    "रीसेट कूपन",
    "उपयोग किया गया",
    "समाप्त",
    "उपयोग पूर्वानुमान",
    "उपयोग पूर्वानुमान",
    "उपयोग पूर्वानुमान इतिहास साफ़ करें",
    "उपयोग पूर्वानुमान इतिहास साफ़ करें?",
];

const GERMAN_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Abfrage läuft",
    "Aktualisieren",
    "Nutzungsdaten sind veraltet",
    "Nutzung nicht verfügbar",
    "Aktualisieren",
    "Jetzt aktualisieren",
    "Aktualisierungsintervall",
    "Mit Windows starten",
    "Startansicht",
    "Widget anzeigen",
    "Nur Infobereich",
    "Automatische Authentifizierung aktualisieren",
    "Bei Codex anmelden",
    "Authentifizierung aktualisieren",
    "Sprache",
    "Automatisch",
    "Diagnose",
    "Nach Updates suchen",
    "Einstellungen",
    "Beenden",
    "Widget anzeigen",
    "Widget ausblenden",
    "Start: Widget anzeigen",
    "Start: nur Infobereich",
    "Widget: alle Monitore",
    "Widget: nur Hauptmonitor",
    "Widget-Position",
    "Alle Monitore",
    "Nur Hauptmonitor",
    "Ein Update ist verfügbar",
    "Sie sind auf dem neuesten Stand",
    "Updates werden gesucht",
    "Updateprüfung fehlgeschlagen",
    "Codex-Nutzungsmonitor",
    "Einstellungen für Codex-Nutzungsmonitor",
    "Diagnose des Codex-Nutzungsmonitors",
    "Hauptfenster",
    "Nebenfenster",
    "Codex CLI konnte nicht verifiziert werden",
    "Codex-Dienstanforderung fehlgeschlagen",
    "Anmeldestatus konnte nicht verifiziert werden",
    "Einstellungen konnten nicht gelesen oder validiert werden",
    "Proxy-Präsenz wurde geprüft",
    "Taskleistenstatus konnte nicht verifiziert werden",
    "Verbleibende Nutzung anzeigen",
    "Wöchentliche Nutzung anzeigen",
    "Version {version} ist verfügbar.\n\nGitHub-Release-Seite öffnen?",
    "Die Updateprüfung ist fehlgeschlagen. Prüfen Sie die Netzwerk- oder Proxy-Einstellungen und versuchen Sie es erneut.",
    "Die GitHub-Release-Seite konnte nicht geöffnet werden. Prüfen Sie die Einstellungen des Standardbrowsers.",
    "Nutzungsprofile",
    "Nutzungsprofil hinzufügen",
    "Nutzungsprofile verwalten",
    "Standard-Codex-Konto",
    "Angezeigt",
    "Die Codex-CLI-Anmeldung bleibt unverändert",
    "Anmeldung erforderlich",
    "Nutzungsprofil hinzufügen",
    "Bestätigen Sie im Browser das zu verwendende Konto",
    "Umbenennen",
    "Anmelden",
    "Abmelden",
    "Löschen",
    "Dieses Nutzungsprofil löschen?",
    "Das Limit für Nutzungsprofile ist erreicht",
    "Schließen",
    "Profilname",
    "Überprüfen Sie den Profilnamen",
    "Codex-CLI- und IDE-Anmeldungen bleiben unverändert",
    "Lokale Profildaten können nicht wiederhergestellt werden",
    "Der Profilvorgang konnte nicht abgeschlossen werden",
    "Abbrechen",
    "Zurücksetzungsgutscheine",
    "verwendet",
    "endet",
    "Nutzungsprognose",
    "Nutzungsprognose",
    "Nutzungsprognoseverlauf löschen",
    "Nutzungsprognoseverlauf löschen?",
];

const FRENCH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Interrogation",
    "Actualisation",
    "Les données d'utilisation sont obsolètes",
    "Utilisation indisponible",
    "Actualiser",
    "Actualiser maintenant",
    "Intervalle d'actualisation",
    "Démarrer avec Windows",
    "Vue au démarrage",
    "Afficher le widget",
    "Zone de notification seule",
    "Actualisation automatique de l'authentification",
    "Se connecter à Codex",
    "Actualiser l'authentification",
    "Langue",
    "Automatique",
    "Diagnostics",
    "Rechercher des mises à jour",
    "Paramètres",
    "Quitter",
    "Afficher le widget",
    "Masquer le widget",
    "Démarrage: afficher le widget",
    "Démarrage: zone de notification seule",
    "Widget: tous les moniteurs",
    "Widget: moniteur principal seul",
    "Emplacement du widget",
    "Tous les moniteurs",
    "Moniteur principal seul",
    "Une mise à jour est disponible",
    "Vous êtes à jour",
    "Recherche de mises à jour",
    "Échec de la recherche de mises à jour",
    "Moniteur d'utilisation Codex",
    "Paramètres du moniteur d'utilisation Codex",
    "Diagnostics du moniteur d'utilisation Codex",
    "Fenêtre principale",
    "Fenêtre secondaire",
    "Codex CLI n'a pas pu être vérifié",
    "La requête du service Codex a échoué",
    "L'état de connexion n'a pas pu être vérifié",
    "Les paramètres n'ont pas pu être lus ou validés",
    "La présence d'un proxy a été vérifiée",
    "L'état de la barre des tâches n'a pas pu être vérifié",
    "Afficher l'utilisation restante",
    "Afficher l'utilisation hebdomadaire",
    "La version {version} est disponible.\n\nOuvrir la page de version GitHub ?",
    "La recherche de mises à jour a échoué. Vérifiez les paramètres réseau ou proxy, puis réessayez.",
    "Impossible d'ouvrir la page de version GitHub. Vérifiez les paramètres du navigateur par défaut.",
    "Profils d'utilisation",
    "Ajouter un profil d'utilisation",
    "Gérer les profils d'utilisation",
    "Compte Codex par défaut",
    "Affiché",
    "La connexion à Codex CLI reste inchangée",
    "Connexion requise",
    "Ajouter un profil d'utilisation",
    "Confirmez dans le navigateur le compte à utiliser",
    "Renommer",
    "Se connecter",
    "Se déconnecter",
    "Supprimer",
    "Supprimer ce profil d'utilisation ?",
    "La limite de profils d'utilisation est atteinte",
    "Fermer",
    "Nom du profil",
    "Vérifiez le nom du profil",
    "Les connexions à Codex CLI et à l'IDE restent inchangées",
    "Les données locales du profil sont irrécupérables",
    "L'opération de profil n'a pas pu être effectuée",
    "Annuler",
    "Coupons de réinitialisation",
    "utilisé",
    "se termine",
    "Prévision d'utilisation",
    "Prévision d'utilisation",
    "Effacer l'historique des prévisions d'utilisation",
    "Effacer l'historique des prévisions d'utilisation ?",
];

const VIETNAMESE_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Đang thăm dò",
    "Đang làm mới",
    "Dữ liệu sử dụng đã cũ",
    "Không có thông tin sử dụng",
    "Làm mới",
    "Làm mới ngay",
    "Khoảng thời gian làm mới",
    "Khởi động cùng Windows",
    "Màn hình khởi động",
    "Hiển thị widget",
    "Chỉ khay hệ thống",
    "Tự động làm mới xác thực",
    "Đăng nhập vào Codex",
    "Làm mới xác thực",
    "Ngôn ngữ",
    "Tự động",
    "Chẩn đoán",
    "Kiểm tra cập nhật",
    "Cài đặt",
    "Thoát",
    "Hiển thị widget",
    "Ẩn widget",
    "Khởi động: hiển thị widget",
    "Khởi động: chỉ khay hệ thống",
    "Widget: tất cả màn hình",
    "Widget: chỉ màn hình chính",
    "Vị trí widget",
    "Tất cả màn hình",
    "Chỉ màn hình chính",
    "Có bản cập nhật mới",
    "Bạn đang dùng phiên bản mới nhất",
    "Đang kiểm tra cập nhật",
    "Kiểm tra cập nhật thất bại",
    "Bộ theo dõi sử dụng Codex",
    "Cài đặt bộ theo dõi sử dụng Codex",
    "Chẩn đoán bộ theo dõi sử dụng Codex",
    "Cửa sổ chính",
    "Cửa sổ phụ",
    "Không thể xác minh Codex CLI",
    "Yêu cầu dịch vụ Codex thất bại",
    "Không thể xác minh trạng thái đăng nhập",
    "Không thể đọc hoặc xác thực cài đặt",
    "Đã kiểm tra sự hiện diện của proxy",
    "Không thể xác minh trạng thái thanh tác vụ",
    "Hiển thị mức sử dụng còn lại",
    "Hiển thị mức sử dụng hằng tuần",
    "Phiên bản {version} hiện có.\n\nMở trang bản phát hành GitHub?",
    "Kiểm tra cập nhật không thành công. Hãy kiểm tra cài đặt mạng hoặc proxy rồi thử lại.",
    "Không thể mở trang bản phát hành GitHub. Hãy kiểm tra cài đặt trình duyệt mặc định.",
    "Hồ sơ sử dụng",
    "Thêm hồ sơ sử dụng",
    "Quản lý hồ sơ sử dụng",
    "Tài khoản Codex mặc định",
    "Đang hiển thị",
    "Đăng nhập Codex CLI không thay đổi",
    "Cần đăng nhập",
    "Thêm hồ sơ sử dụng",
    "Xác nhận tài khoản sẽ dùng trong trình duyệt",
    "Đổi tên",
    "Đăng nhập",
    "Đăng xuất",
    "Xóa",
    "Xóa hồ sơ sử dụng này?",
    "Đã đạt giới hạn hồ sơ sử dụng",
    "Đóng",
    "Tên hồ sơ",
    "Kiểm tra tên hồ sơ",
    "Đăng nhập Codex CLI và IDE không thay đổi",
    "Không thể khôi phục dữ liệu hồ sơ cục bộ",
    "Không thể hoàn tất thao tác hồ sơ",
    "Hủy",
    "Phiếu đặt lại",
    "đã dùng",
    "kết thúc",
    "Dự báo sử dụng",
    "Dự báo sử dụng",
    "Xóa lịch sử dự báo sử dụng",
    "Xóa lịch sử dự báo sử dụng?",
];

const TURKISH_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "Sorgulanıyor",
    "Yenileniyor",
    "Kullanım verileri eski",
    "Kullanım kullanılamıyor",
    "Yenile",
    "Şimdi yenile",
    "Yenileme aralığı",
    "Windows ile başlat",
    "Başlangıç görünümü",
    "Widget'ı göster",
    "Yalnızca tepsi",
    "Otomatik kimlik doğrulama yenileme",
    "Codex'te oturum aç",
    "Kimlik doğrulamayı yenile",
    "Dil",
    "Otomatik",
    "Tanılama",
    "Güncellemeleri denetle",
    "Ayarlar",
    "Çıkış",
    "Widget'ı göster",
    "Widget'ı gizle",
    "Başlangıç: widget'ı göster",
    "Başlangıç: yalnızca tepsi",
    "Widget: tüm monitörler",
    "Widget: yalnızca ana monitör",
    "Widget konumu",
    "Tüm monitörler",
    "Yalnızca ana monitör",
    "Bir güncelleme mevcut",
    "Güncelsiniz",
    "Güncellemeler denetleniyor",
    "Güncelleme denetimi başarısız",
    "Codex Kullanım Monitörü",
    "Codex Kullanım Monitörü Ayarları",
    "Codex Kullanım Monitörü Tanılaması",
    "Birincil pencere",
    "İkincil pencere",
    "Codex CLI doğrulanamadı",
    "Codex hizmet isteği başarısız",
    "Oturum açma durumu doğrulanamadı",
    "Ayarlar okunamadı veya doğrulanamadı",
    "Proxy varlığı denetlendi",
    "Görev çubuğu durumu doğrulanamadı",
    "Kalan kullanımı göster",
    "Haftalık kullanımı göster",
    "{version} sürümü kullanılabilir.\n\nGitHub sürüm sayfası açılsın mı?",
    "Güncelleme denetimi başarısız oldu. Ağ veya proxy ayarlarını denetleyip yeniden deneyin.",
    "GitHub sürüm sayfası açılamadı. Varsayılan tarayıcı ayarlarını denetleyin.",
    "Kullanım profilleri",
    "Kullanım profili ekle",
    "Kullanım profillerini yönet",
    "Varsayılan Codex hesabı",
    "Gösteriliyor",
    "Codex CLI oturumu değişmez",
    "Oturum açılması gerekiyor",
    "Kullanım profili ekle",
    "Tarayıcıda kullanılacak hesabı doğrulayın",
    "Yeniden adlandır",
    "Oturum aç",
    "Oturumu kapat",
    "Sil",
    "Bu kullanım profili silinsin mi?",
    "Kullanım profili sınırına ulaşıldı",
    "Kapat",
    "Profil adı",
    "Profil adını kontrol edin",
    "Codex CLI ve IDE oturumları değişmez",
    "Yerel profil verileri kurtarılamaz",
    "Profil işlemi tamamlanamadı",
    "İptal",
    "Sıfırlama kuponları",
    "kullanıldı",
    "biter",
    "Kullanım tahmini",
    "Kullanım tahmini",
    "Kullanım tahmin geçmişini temizle",
    "Kullanım tahmin geçmişi temizlensin mi?",
];

const ARABIC_TEXT: [&str; LOCALIZATION_KEY_COUNT] = [
    "جارٍ الاستعلام",
    "جارٍ التحديث",
    "بيانات الاستخدام قديمة",
    "الاستخدام غير متاح",
    "تحديث",
    "تحديث الآن",
    "فاصل التحديث",
    "البدء مع Windows",
    "عرض بدء التشغيل",
    "إظهار الويدجت",
    "علبة النظام فقط",
    "تحديث المصادقة تلقائيًا",
    "تسجيل الدخول إلى Codex",
    "تحديث المصادقة",
    "اللغة",
    "تلقائي",
    "التشخيصات",
    "التحقق من التحديثات",
    "الإعدادات",
    "خروج",
    "إظهار الويدجت",
    "إخفاء الويدجت",
    "بدء التشغيل: إظهار الويدجت",
    "بدء التشغيل: علبة النظام فقط",
    "الويدجت: كل الشاشات",
    "الويدجت: الشاشة الرئيسية فقط",
    "موضع الويدجت",
    "كل الشاشات",
    "الشاشة الرئيسية فقط",
    "يتوفر تحديث جديد",
    "أنت تستخدم أحدث إصدار",
    "جارٍ التحقق من التحديثات",
    "فشل التحقق من التحديثات",
    "مراقب استخدام Codex",
    "إعدادات مراقب استخدام Codex",
    "تشخيصات مراقب استخدام Codex",
    "النافذة الرئيسية",
    "النافذة الثانوية",
    "تعذر التحقق من Codex CLI",
    "فشل طلب خدمة Codex",
    "تعذر التحقق من حالة تسجيل الدخول",
    "تعذرت قراءة الإعدادات أو التحقق منها",
    "تم التحقق من وجود الوكيل",
    "تعذر التحقق من حالة شريط المهام",
    "إظهار الاستخدام المتبقي",
    "إظهار الاستخدام الأسبوعي",
    "الإصدار {version} متاح.\n\nهل تريد فتح صفحة الإصدار على GitHub؟",
    "فشل التحقق من التحديث. تحقق من إعدادات الشبكة أو الوكيل ثم أعد المحاولة.",
    "تعذر فتح صفحة الإصدار على GitHub. تحقق من إعدادات المتصفح الافتراضي.",
    "ملفات تعريف الاستخدام",
    "إضافة ملف تعريف استخدام",
    "إدارة ملفات تعريف الاستخدام",
    "حساب Codex الافتراضي",
    "معروض",
    "لا يتغير تسجيل الدخول إلى Codex CLI",
    "تسجيل الدخول مطلوب",
    "إضافة ملف تعريف استخدام",
    "أكد الحساب المراد استخدامه في المتصفح",
    "إعادة التسمية",
    "تسجيل الدخول",
    "تسجيل الخروج",
    "حذف",
    "هل تريد حذف ملف تعريف الاستخدام هذا؟",
    "تم بلوغ حد ملفات تعريف الاستخدام",
    "إغلاق",
    "اسم ملف التعريف",
    "تحقق من اسم ملف التعريف",
    "لا تتغير عمليات تسجيل الدخول في Codex CLI وIDE",
    "لا يمكن استعادة بيانات ملف التعريف المحلية",
    "تعذر إكمال عملية ملف التعريف",
    "إلغاء",
    "قسائم إعادة التعيين",
    "مستخدم",
    "ينتهي",
    "توقع الاستخدام",
    "توقع الاستخدام",
    "مسح سجل توقع الاستخدام",
    "هل تريد مسح سجل توقع الاستخدام؟",
];

/// 지정한 언어와 키에 해당하는 정적 사용자 문구를 반환합니다.
///
/// 매개변수 `key`는 표시할 문구 식별자이고 `language`는 반환 언어입니다.
/// 반환값은 프로그램 전체에서 재사용 가능한 정적 문자열입니다.
pub fn localized_text(key: LocalizationKey, language: Language) -> &'static str {
    let index = key.index();
    match language {
        Language::Korean => KOREAN_TEXT[index],
        Language::English => ENGLISH_TEXT[index],
        Language::Spanish => SPANISH_TEXT[index],
        Language::PortugueseBrazil => PORTUGUESE_BRAZIL_TEXT[index],
        Language::Indonesian => INDONESIAN_TEXT[index],
        Language::Japanese => JAPANESE_TEXT[index],
        Language::Hindi => HINDI_TEXT[index],
        Language::German => GERMAN_TEXT[index],
        Language::French => FRENCH_TEXT[index],
        Language::Vietnamese => VIETNAMESE_TEXT[index],
        Language::Turkish => TURKISH_TEXT[index],
        Language::Arabic => ARABIC_TEXT[index],
    }
}

/// 갱신 간격 값을 하위 메뉴의 짧은 선택 문구로 만듭니다.
///
/// `minutes`는 지원되는 자동 갱신 간격이며, 호출자가 메뉴 동작 검증을 별도로 수행합니다.
pub(crate) fn localized_refresh_interval_choice_text(minutes: u32, language: Language) -> String {
    match language {
        Language::Korean => format!("{minutes}분"),
        Language::English | Language::Spanish | Language::PortugueseBrazil | Language::French => {
            format!("{minutes} min")
        }
        Language::Indonesian => format!("{minutes} mnt"),
        Language::Japanese => format!("{minutes}分"),
        Language::Hindi => format!("{minutes} मिनट"),
        Language::German => format!("{minutes} Min."),
        Language::Vietnamese => format!("{minutes} phút"),
        Language::Turkish => format!("{minutes} dk"),
        Language::Arabic => format!("{minutes} دقيقة"),
    }
}

#[cfg(test)]
mod tests {
    use super::{
        localized_refresh_interval_choice_text, localized_text, Language, LocalizationKey,
    };

    #[test]
    fn every_key_has_a_nonempty_translation() {
        for key in LocalizationKey::ALL {
            for language in Language::ALL {
                assert!(!localized_text(*key, *language).trim().is_empty());
            }
        }
    }

    #[test]
    fn refresh_interval_choice_text_includes_value_and_unit() {
        assert_eq!(
            localized_refresh_interval_choice_text(15, Language::Korean),
            "15분"
        );
        assert_eq!(
            localized_refresh_interval_choice_text(15, Language::English),
            "15 min"
        );
        for language in Language::ALL {
            let text = localized_refresh_interval_choice_text(15, *language);
            assert!(text.contains("15"), "{language:?}: {text}");
        }
    }
}
